// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/user (interfaces: CreateUserPort,DeleteUserPort,GetUserPort)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/user/mocks/ports.go -package=mocks . CreateUserPort,DeleteUserPort,GetUserPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	user "backend/internal/user"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCreateUserPort is a mock of CreateUserPort interface.
type MockCreateUserPort struct {
	ctrl     *gomock.Controller
	recorder *MockCreateUserPortMockRecorder
	isgomock struct{}
}

// MockCreateUserPortMockRecorder is the mock recorder for MockCreateUserPort.
type MockCreateUserPortMockRecorder struct {
	mock *MockCreateUserPort
}

// NewMockCreateUserPort creates a new mock instance.
func NewMockCreateUserPort(ctrl *gomock.Controller) *MockCreateUserPort {
	mock := &MockCreateUserPort{ctrl: ctrl}
	mock.recorder = &MockCreateUserPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateUserPort) EXPECT() *MockCreateUserPortMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockCreateUserPort) CreateUser(arg0 user.User) (user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0)
	ret0, _ := ret[0].(user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockCreateUserPortMockRecorder) CreateUser(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockCreateUserPort)(nil).CreateUser), arg0)
}

// MockDeleteUserPort is a mock of DeleteUserPort interface.
type MockDeleteUserPort struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteUserPortMockRecorder
	isgomock struct{}
}

// MockDeleteUserPortMockRecorder is the mock recorder for MockDeleteUserPort.
type MockDeleteUserPortMockRecorder struct {
	mock *MockDeleteUserPort
}

// NewMockDeleteUserPort creates a new mock instance.
func NewMockDeleteUserPort(ctrl *gomock.Controller) *MockDeleteUserPort {
	mock := &MockDeleteUserPort{ctrl: ctrl}
	mock.recorder = &MockDeleteUserPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteUserPort) EXPECT() *MockDeleteUserPortMockRecorder {
	return m.recorder
}

// DeleteSuperAdmin mocks base method.
func (m *MockDeleteUserPort) DeleteSuperAdmin(userId uint) (user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSuperAdmin", userId)
	ret0, _ := ret[0].(user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteSuperAdmin indicates an expected call of DeleteSuperAdmin.
func (mr *MockDeleteUserPortMockRecorder) DeleteSuperAdmin(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSuperAdmin", reflect.TypeOf((*MockDeleteUserPort)(nil).DeleteSuperAdmin), userId)
}

// DeleteTenantAdmin mocks base method.
func (m *MockDeleteUserPort) DeleteTenantAdmin(tenantId uuid.UUID, userId uint) (user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTenantAdmin", tenantId, userId)
	ret0, _ := ret[0].(user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTenantAdmin indicates an expected call of DeleteTenantAdmin.
func (mr *MockDeleteUserPortMockRecorder) DeleteTenantAdmin(tenantId, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTenantAdmin", reflect.TypeOf((*MockDeleteUserPort)(nil).DeleteTenantAdmin), tenantId, userId)
}

// DeleteTenantUser mocks base method.
func (m *MockDeleteUserPort) DeleteTenantUser(tenantId uuid.UUID, userId uint) (user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTenantUser", tenantId, userId)
	ret0, _ := ret[0].(user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTenantUser indicates an expected call of DeleteTenantUser.
func (mr *MockDeleteUserPortMockRecorder) DeleteTenantUser(tenantId, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTenantUser", reflect.TypeOf((*MockDeleteUserPort)(nil).DeleteTenantUser), tenantId, userId)
}

// MockGetUserPort is a mock of GetUserPort interface.
type MockGetUserPort struct {
	ctrl     *gomock.Controller
	recorder *MockGetUserPortMockRecorder
	isgomock struct{}
}

// MockGetUserPortMockRecorder is the mock recorder for MockGetUserPort.
type MockGetUserPortMockRecorder struct {
	mock *MockGetUserPort
}

// NewMockGetUserPort creates a new mock instance.
func NewMockGetUserPort(ctrl *gomock.Controller) *MockGetUserPort {
	mock := &MockGetUserPort{ctrl: ctrl}
	mock.recorder = &MockGetUserPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetUserPort) EXPECT() *MockGetUserPortMockRecorder {
	return m.recorder
}

// GetSuperAdmin mocks base method.
func (m *MockGetUserPort) GetSuperAdmin(userId uint) (user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSuperAdmin", userId)
	ret0, _ := ret[0].(user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSuperAdmin indicates an expected call of GetSuperAdmin.
func (mr *MockGetUserPortMockRecorder) GetSuperAdmin(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSuperAdmin", reflect.TypeOf((*MockGetUserPort)(nil).GetSuperAdmin), userId)
}

// GetSuperAdminByEmail mocks base method.
func (m *MockGetUserPort) GetSuperAdminByEmail(email string) (user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSuperAdminByEmail", email)
	ret0, _ := ret[0].(user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSuperAdminByEmail indicates an expected call of GetSuperAdminByEmail.
func (mr *MockGetUserPortMockRecorder) GetSuperAdminByEmail(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSuperAdminByEmail", reflect.TypeOf((*MockGetUserPort)(nil).GetSuperAdminByEmail), email)
}

// GetSuperAdminList mocks base method.
func (m *MockGetUserPort) GetSuperAdminList(page, limit int) ([]user.User, uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSuperAdminList", page, limit)
	ret0, _ := ret[0].([]user.User)
	ret1, _ := ret[1].(uint)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSuperAdminList indicates an expected call of GetSuperAdminList.
func (mr *MockGetUserPortMockRecorder) GetSuperAdminList(page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSuperAdminList", reflect.TypeOf((*MockGetUserPort)(nil).GetSuperAdminList), page, limit)
}

// GetTenantAdmin mocks base method.
func (m *MockGetUserPort) GetTenantAdmin(tenantId uuid.UUID, userId uint) (user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenantAdmin", tenantId, userId)
	ret0, _ := ret[0].(user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenantAdmin indicates an expected call of GetTenantAdmin.
func (mr *MockGetUserPortMockRecorder) GetTenantAdmin(tenantId, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenantAdmin", reflect.TypeOf((*MockGetUserPort)(nil).GetTenantAdmin), tenantId, userId)
}

// GetTenantAdminByEmail mocks base method.
func (m *MockGetUserPort) GetTenantAdminByEmail(tenantId uuid.UUID, email string) (user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenantAdminByEmail", tenantId, email)
	ret0, _ := ret[0].(user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenantAdminByEmail indicates an expected call of GetTenantAdminByEmail.
func (mr *MockGetUserPortMockRecorder) GetTenantAdminByEmail(tenantId, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenantAdminByEmail", reflect.TypeOf((*MockGetUserPort)(nil).GetTenantAdminByEmail), tenantId, email)
}

// GetTenantAdminsByTenant mocks base method.
func (m *MockGetUserPort) GetTenantAdminsByTenant(tenantId uuid.UUID, page, limit int) ([]user.User, uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenantAdminsByTenant", tenantId, page, limit)
	ret0, _ := ret[0].([]user.User)
	ret1, _ := ret[1].(uint)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTenantAdminsByTenant indicates an expected call of GetTenantAdminsByTenant.
func (mr *MockGetUserPortMockRecorder) GetTenantAdminsByTenant(tenantId, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenantAdminsByTenant", reflect.TypeOf((*MockGetUserPort)(nil).GetTenantAdminsByTenant), tenantId, page, limit)
}

// GetTenantUser mocks base method.
func (m *MockGetUserPort) GetTenantUser(tenantId uuid.UUID, userId uint) (user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenantUser", tenantId, userId)
	ret0, _ := ret[0].(user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenantUser indicates an expected call of GetTenantUser.
func (mr *MockGetUserPortMockRecorder) GetTenantUser(tenantId, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenantUser", reflect.TypeOf((*MockGetUserPort)(nil).GetTenantUser), tenantId, userId)
}

// GetTenantUserByEmail mocks base method.
func (m *MockGetUserPort) GetTenantUserByEmail(tenantId uuid.UUID, email string) (user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenantUserByEmail", tenantId, email)
	ret0, _ := ret[0].(user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenantUserByEmail indicates an expected call of GetTenantUserByEmail.
func (mr *MockGetUserPortMockRecorder) GetTenantUserByEmail(tenantId, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenantUserByEmail", reflect.TypeOf((*MockGetUserPort)(nil).GetTenantUserByEmail), tenantId, email)
}

// GetTenantUsersByTenant mocks base method.
func (m *MockGetUserPort) GetTenantUsersByTenant(tenantId uuid.UUID, page, limit int) ([]user.User, uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenantUsersByTenant", tenantId, page, limit)
	ret0, _ := ret[0].([]user.User)
	ret1, _ := ret[1].(uint)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTenantUsersByTenant indicates an expected call of GetTenantUsersByTenant.
func (mr *MockGetUserPortMockRecorder) GetTenantUsersByTenant(tenantId, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenantUsersByTenant", reflect.TypeOf((*MockGetUserPort)(nil).GetTenantUsersByTenant), tenantId, page, limit)
}
