// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/user (interfaces: GenerateTokenPort,SendConfirmAccountEmailPort)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/user/mocks/ports_create.go -package=mocks . GenerateTokenPort,SendConfirmAccountEmailPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	user "backend/internal/user"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGenerateTokenPort is a mock of GenerateTokenPort interface.
type MockGenerateTokenPort struct {
	ctrl     *gomock.Controller
	recorder *MockGenerateTokenPortMockRecorder
	isgomock struct{}
}

// MockGenerateTokenPortMockRecorder is the mock recorder for MockGenerateTokenPort.
type MockGenerateTokenPortMockRecorder struct {
	mock *MockGenerateTokenPort
}

// NewMockGenerateTokenPort creates a new mock instance.
func NewMockGenerateTokenPort(ctrl *gomock.Controller) *MockGenerateTokenPort {
	mock := &MockGenerateTokenPort{ctrl: ctrl}
	mock.recorder = &MockGenerateTokenPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenerateTokenPort) EXPECT() *MockGenerateTokenPortMockRecorder {
	return m.recorder
}

// NewConfirmAccountToken mocks base method.
func (m *MockGenerateTokenPort) NewConfirmAccountToken(arg0 user.User) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewConfirmAccountToken", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewConfirmAccountToken indicates an expected call of NewConfirmAccountToken.
func (mr *MockGenerateTokenPortMockRecorder) NewConfirmAccountToken(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewConfirmAccountToken", reflect.TypeOf((*MockGenerateTokenPort)(nil).NewConfirmAccountToken), arg0)
}

// MockSendConfirmAccountEmailPort is a mock of SendConfirmAccountEmailPort interface.
type MockSendConfirmAccountEmailPort struct {
	ctrl     *gomock.Controller
	recorder *MockSendConfirmAccountEmailPortMockRecorder
	isgomock struct{}
}

// MockSendConfirmAccountEmailPortMockRecorder is the mock recorder for MockSendConfirmAccountEmailPort.
type MockSendConfirmAccountEmailPortMockRecorder struct {
	mock *MockSendConfirmAccountEmailPort
}

// NewMockSendConfirmAccountEmailPort creates a new mock instance.
func NewMockSendConfirmAccountEmailPort(ctrl *gomock.Controller) *MockSendConfirmAccountEmailPort {
	mock := &MockSendConfirmAccountEmailPort{ctrl: ctrl}
	mock.recorder = &MockSendConfirmAccountEmailPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSendConfirmAccountEmailPort) EXPECT() *MockSendConfirmAccountEmailPortMockRecorder {
	return m.recorder
}

// SendConfirmAccountEmail mocks base method.
func (m *MockSendConfirmAccountEmailPort) SendConfirmAccountEmail(toAddr, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendConfirmAccountEmail", toAddr, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendConfirmAccountEmail indicates an expected call of SendConfirmAccountEmail.
func (mr *MockSendConfirmAccountEmailPortMockRecorder) SendConfirmAccountEmail(toAddr, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendConfirmAccountEmail", reflect.TypeOf((*MockSendConfirmAccountEmailPort)(nil).SendConfirmAccountEmail), toAddr, token)
}
