// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/user (interfaces: SuperAdminRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/user/mocks/repository_super_admin.go -package=mocks . SuperAdminRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	user "backend/internal/user"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSuperAdminRepository is a mock of SuperAdminRepository interface.
type MockSuperAdminRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSuperAdminRepositoryMockRecorder
	isgomock struct{}
}

// MockSuperAdminRepositoryMockRecorder is the mock recorder for MockSuperAdminRepository.
type MockSuperAdminRepositoryMockRecorder struct {
	mock *MockSuperAdminRepository
}

// NewMockSuperAdminRepository creates a new mock instance.
func NewMockSuperAdminRepository(ctrl *gomock.Controller) *MockSuperAdminRepository {
	mock := &MockSuperAdminRepository{ctrl: ctrl}
	mock.recorder = &MockSuperAdminRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSuperAdminRepository) EXPECT() *MockSuperAdminRepositoryMockRecorder {
	return m.recorder
}

// CountSuperAdmins mocks base method.
func (m *MockSuperAdminRepository) CountSuperAdmins() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountSuperAdmins")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountSuperAdmins indicates an expected call of CountSuperAdmins.
func (mr *MockSuperAdminRepositoryMockRecorder) CountSuperAdmins() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountSuperAdmins", reflect.TypeOf((*MockSuperAdminRepository)(nil).CountSuperAdmins))
}

// DeleteSuperAdmin mocks base method.
func (m *MockSuperAdminRepository) DeleteSuperAdmin(superAdmin *user.SuperAdminEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSuperAdmin", superAdmin)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSuperAdmin indicates an expected call of DeleteSuperAdmin.
func (mr *MockSuperAdminRepositoryMockRecorder) DeleteSuperAdmin(superAdmin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSuperAdmin", reflect.TypeOf((*MockSuperAdminRepository)(nil).DeleteSuperAdmin), superAdmin)
}

// GetSuperAdmin mocks base method.
func (m *MockSuperAdminRepository) GetSuperAdmin(by user.UserRepositoryGetUserBy) (*user.SuperAdminEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSuperAdmin", by)
	ret0, _ := ret[0].(*user.SuperAdminEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSuperAdmin indicates an expected call of GetSuperAdmin.
func (mr *MockSuperAdminRepositoryMockRecorder) GetSuperAdmin(by any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSuperAdmin", reflect.TypeOf((*MockSuperAdminRepository)(nil).GetSuperAdmin), by)
}

// GetSuperAdmins mocks base method.
func (m *MockSuperAdminRepository) GetSuperAdmins(offset, limit int) ([]user.SuperAdminEntity, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSuperAdmins", offset, limit)
	ret0, _ := ret[0].([]user.SuperAdminEntity)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSuperAdmins indicates an expected call of GetSuperAdmins.
func (mr *MockSuperAdminRepositoryMockRecorder) GetSuperAdmins(offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSuperAdmins", reflect.TypeOf((*MockSuperAdminRepository)(nil).GetSuperAdmins), offset, limit)
}

// SaveSuperAdmin mocks base method.
func (m *MockSuperAdminRepository) SaveSuperAdmin(superAdmin *user.SuperAdminEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSuperAdmin", superAdmin)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSuperAdmin indicates an expected call of SaveSuperAdmin.
func (mr *MockSuperAdminRepositoryMockRecorder) SaveSuperAdmin(superAdmin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSuperAdmin", reflect.TypeOf((*MockSuperAdminRepository)(nil).SaveSuperAdmin), superAdmin)
}
