// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/user (interfaces: TenantMemberRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/user/mocks/repository_tenant_member.go -package=mocks . TenantMemberRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	user "backend/internal/user"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTenantMemberRepository is a mock of TenantMemberRepository interface.
type MockTenantMemberRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTenantMemberRepositoryMockRecorder
	isgomock struct{}
}

// MockTenantMemberRepositoryMockRecorder is the mock recorder for MockTenantMemberRepository.
type MockTenantMemberRepositoryMockRecorder struct {
	mock *MockTenantMemberRepository
}

// NewMockTenantMemberRepository creates a new mock instance.
func NewMockTenantMemberRepository(ctrl *gomock.Controller) *MockTenantMemberRepository {
	mock := &MockTenantMemberRepository{ctrl: ctrl}
	mock.recorder = &MockTenantMemberRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantMemberRepository) EXPECT() *MockTenantMemberRepositoryMockRecorder {
	return m.recorder
}

// CountTenantAdminsByTenant mocks base method.
func (m *MockTenantMemberRepository) CountTenantAdminsByTenant(tenantId string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTenantAdminsByTenant", tenantId)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTenantAdminsByTenant indicates an expected call of CountTenantAdminsByTenant.
func (mr *MockTenantMemberRepositoryMockRecorder) CountTenantAdminsByTenant(tenantId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTenantAdminsByTenant", reflect.TypeOf((*MockTenantMemberRepository)(nil).CountTenantAdminsByTenant), tenantId)
}

// DeleteTenantMember mocks base method.
func (m *MockTenantMemberRepository) DeleteTenantMember(tenantMember *user.TenantMemberEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTenantMember", tenantMember)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTenantMember indicates an expected call of DeleteTenantMember.
func (mr *MockTenantMemberRepositoryMockRecorder) DeleteTenantMember(tenantMember any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTenantMember", reflect.TypeOf((*MockTenantMemberRepository)(nil).DeleteTenantMember), tenantMember)
}

// GetTenantAdmins mocks base method.
func (m *MockTenantMemberRepository) GetTenantAdmins(tenantId string, offset, limit int) ([]user.TenantMemberEntity, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenantAdmins", tenantId, offset, limit)
	ret0, _ := ret[0].([]user.TenantMemberEntity)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTenantAdmins indicates an expected call of GetTenantAdmins.
func (mr *MockTenantMemberRepositoryMockRecorder) GetTenantAdmins(tenantId, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenantAdmins", reflect.TypeOf((*MockTenantMemberRepository)(nil).GetTenantAdmins), tenantId, offset, limit)
}

// GetTenantMember mocks base method.
func (m *MockTenantMemberRepository) GetTenantMember(tenantId string, by user.UserRepositoryGetUserBy) (*user.TenantMemberEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenantMember", tenantId, by)
	ret0, _ := ret[0].(*user.TenantMemberEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenantMember indicates an expected call of GetTenantMember.
func (mr *MockTenantMemberRepositoryMockRecorder) GetTenantMember(tenantId, by any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenantMember", reflect.TypeOf((*MockTenantMemberRepository)(nil).GetTenantMember), tenantId, by)
}

// GetTenantUsers mocks base method.
func (m *MockTenantMemberRepository) GetTenantUsers(tenantId string, offset, limit int) ([]user.TenantMemberEntity, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenantUsers", tenantId, offset, limit)
	ret0, _ := ret[0].([]user.TenantMemberEntity)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTenantUsers indicates an expected call of GetTenantUsers.
func (mr *MockTenantMemberRepositoryMockRecorder) GetTenantUsers(tenantId, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenantUsers", reflect.TypeOf((*MockTenantMemberRepository)(nil).GetTenantUsers), tenantId, offset, limit)
}

// SaveTenantMember mocks base method.
func (m *MockTenantMemberRepository) SaveTenantMember(tenantMember *user.TenantMemberEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTenantMember", tenantMember)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveTenantMember indicates an expected call of SaveTenantMember.
func (mr *MockTenantMemberRepositoryMockRecorder) SaveTenantMember(tenantMember any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTenantMember", reflect.TypeOf((*MockTenantMemberRepository)(nil).SaveTenantMember), tenantMember)
}
