// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/user (interfaces: GetTenantUserUseCase,GetTenantAdminUseCase,GetSuperAdminUseCase,GetTenantUsersByTenantUseCase,GetTenantAdminsByTenantUseCase,GetSuperAdminListUseCase)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/user/mocks/use_cases_get.go -package=mocks . GetTenantUserUseCase,GetTenantAdminUseCase,GetSuperAdminUseCase,GetTenantUsersByTenantUseCase,GetTenantAdminsByTenantUseCase,GetSuperAdminListUseCase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	user "backend/internal/user"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGetTenantUserUseCase is a mock of GetTenantUserUseCase interface.
type MockGetTenantUserUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetTenantUserUseCaseMockRecorder
	isgomock struct{}
}

// MockGetTenantUserUseCaseMockRecorder is the mock recorder for MockGetTenantUserUseCase.
type MockGetTenantUserUseCaseMockRecorder struct {
	mock *MockGetTenantUserUseCase
}

// NewMockGetTenantUserUseCase creates a new mock instance.
func NewMockGetTenantUserUseCase(ctrl *gomock.Controller) *MockGetTenantUserUseCase {
	mock := &MockGetTenantUserUseCase{ctrl: ctrl}
	mock.recorder = &MockGetTenantUserUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetTenantUserUseCase) EXPECT() *MockGetTenantUserUseCaseMockRecorder {
	return m.recorder
}

// GetTenantUser mocks base method.
func (m *MockGetTenantUserUseCase) GetTenantUser(cmd user.GetTenantUserCommand) (user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenantUser", cmd)
	ret0, _ := ret[0].(user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenantUser indicates an expected call of GetTenantUser.
func (mr *MockGetTenantUserUseCaseMockRecorder) GetTenantUser(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenantUser", reflect.TypeOf((*MockGetTenantUserUseCase)(nil).GetTenantUser), cmd)
}

// MockGetTenantAdminUseCase is a mock of GetTenantAdminUseCase interface.
type MockGetTenantAdminUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetTenantAdminUseCaseMockRecorder
	isgomock struct{}
}

// MockGetTenantAdminUseCaseMockRecorder is the mock recorder for MockGetTenantAdminUseCase.
type MockGetTenantAdminUseCaseMockRecorder struct {
	mock *MockGetTenantAdminUseCase
}

// NewMockGetTenantAdminUseCase creates a new mock instance.
func NewMockGetTenantAdminUseCase(ctrl *gomock.Controller) *MockGetTenantAdminUseCase {
	mock := &MockGetTenantAdminUseCase{ctrl: ctrl}
	mock.recorder = &MockGetTenantAdminUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetTenantAdminUseCase) EXPECT() *MockGetTenantAdminUseCaseMockRecorder {
	return m.recorder
}

// GetTenantAdmin mocks base method.
func (m *MockGetTenantAdminUseCase) GetTenantAdmin(cmd user.GetTenantAdminCommand) (user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenantAdmin", cmd)
	ret0, _ := ret[0].(user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenantAdmin indicates an expected call of GetTenantAdmin.
func (mr *MockGetTenantAdminUseCaseMockRecorder) GetTenantAdmin(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenantAdmin", reflect.TypeOf((*MockGetTenantAdminUseCase)(nil).GetTenantAdmin), cmd)
}

// MockGetSuperAdminUseCase is a mock of GetSuperAdminUseCase interface.
type MockGetSuperAdminUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetSuperAdminUseCaseMockRecorder
	isgomock struct{}
}

// MockGetSuperAdminUseCaseMockRecorder is the mock recorder for MockGetSuperAdminUseCase.
type MockGetSuperAdminUseCaseMockRecorder struct {
	mock *MockGetSuperAdminUseCase
}

// NewMockGetSuperAdminUseCase creates a new mock instance.
func NewMockGetSuperAdminUseCase(ctrl *gomock.Controller) *MockGetSuperAdminUseCase {
	mock := &MockGetSuperAdminUseCase{ctrl: ctrl}
	mock.recorder = &MockGetSuperAdminUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetSuperAdminUseCase) EXPECT() *MockGetSuperAdminUseCaseMockRecorder {
	return m.recorder
}

// GetSuperAdmin mocks base method.
func (m *MockGetSuperAdminUseCase) GetSuperAdmin(cmd user.GetSuperAdminCommand) (user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSuperAdmin", cmd)
	ret0, _ := ret[0].(user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSuperAdmin indicates an expected call of GetSuperAdmin.
func (mr *MockGetSuperAdminUseCaseMockRecorder) GetSuperAdmin(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSuperAdmin", reflect.TypeOf((*MockGetSuperAdminUseCase)(nil).GetSuperAdmin), cmd)
}

// MockGetTenantUsersByTenantUseCase is a mock of GetTenantUsersByTenantUseCase interface.
type MockGetTenantUsersByTenantUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetTenantUsersByTenantUseCaseMockRecorder
	isgomock struct{}
}

// MockGetTenantUsersByTenantUseCaseMockRecorder is the mock recorder for MockGetTenantUsersByTenantUseCase.
type MockGetTenantUsersByTenantUseCaseMockRecorder struct {
	mock *MockGetTenantUsersByTenantUseCase
}

// NewMockGetTenantUsersByTenantUseCase creates a new mock instance.
func NewMockGetTenantUsersByTenantUseCase(ctrl *gomock.Controller) *MockGetTenantUsersByTenantUseCase {
	mock := &MockGetTenantUsersByTenantUseCase{ctrl: ctrl}
	mock.recorder = &MockGetTenantUsersByTenantUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetTenantUsersByTenantUseCase) EXPECT() *MockGetTenantUsersByTenantUseCaseMockRecorder {
	return m.recorder
}

// GetTenantUsersByTenant mocks base method.
func (m *MockGetTenantUsersByTenantUseCase) GetTenantUsersByTenant(cmd user.GetTenantUsersByTenantCommand) ([]user.User, uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenantUsersByTenant", cmd)
	ret0, _ := ret[0].([]user.User)
	ret1, _ := ret[1].(uint)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTenantUsersByTenant indicates an expected call of GetTenantUsersByTenant.
func (mr *MockGetTenantUsersByTenantUseCaseMockRecorder) GetTenantUsersByTenant(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenantUsersByTenant", reflect.TypeOf((*MockGetTenantUsersByTenantUseCase)(nil).GetTenantUsersByTenant), cmd)
}

// MockGetTenantAdminsByTenantUseCase is a mock of GetTenantAdminsByTenantUseCase interface.
type MockGetTenantAdminsByTenantUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetTenantAdminsByTenantUseCaseMockRecorder
	isgomock struct{}
}

// MockGetTenantAdminsByTenantUseCaseMockRecorder is the mock recorder for MockGetTenantAdminsByTenantUseCase.
type MockGetTenantAdminsByTenantUseCaseMockRecorder struct {
	mock *MockGetTenantAdminsByTenantUseCase
}

// NewMockGetTenantAdminsByTenantUseCase creates a new mock instance.
func NewMockGetTenantAdminsByTenantUseCase(ctrl *gomock.Controller) *MockGetTenantAdminsByTenantUseCase {
	mock := &MockGetTenantAdminsByTenantUseCase{ctrl: ctrl}
	mock.recorder = &MockGetTenantAdminsByTenantUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetTenantAdminsByTenantUseCase) EXPECT() *MockGetTenantAdminsByTenantUseCaseMockRecorder {
	return m.recorder
}

// GetTenantAdminsByTenant mocks base method.
func (m *MockGetTenantAdminsByTenantUseCase) GetTenantAdminsByTenant(cmd user.GetTenantAdminsByTenantCommand) ([]user.User, uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenantAdminsByTenant", cmd)
	ret0, _ := ret[0].([]user.User)
	ret1, _ := ret[1].(uint)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTenantAdminsByTenant indicates an expected call of GetTenantAdminsByTenant.
func (mr *MockGetTenantAdminsByTenantUseCaseMockRecorder) GetTenantAdminsByTenant(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenantAdminsByTenant", reflect.TypeOf((*MockGetTenantAdminsByTenantUseCase)(nil).GetTenantAdminsByTenant), cmd)
}

// MockGetSuperAdminListUseCase is a mock of GetSuperAdminListUseCase interface.
type MockGetSuperAdminListUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetSuperAdminListUseCaseMockRecorder
	isgomock struct{}
}

// MockGetSuperAdminListUseCaseMockRecorder is the mock recorder for MockGetSuperAdminListUseCase.
type MockGetSuperAdminListUseCaseMockRecorder struct {
	mock *MockGetSuperAdminListUseCase
}

// NewMockGetSuperAdminListUseCase creates a new mock instance.
func NewMockGetSuperAdminListUseCase(ctrl *gomock.Controller) *MockGetSuperAdminListUseCase {
	mock := &MockGetSuperAdminListUseCase{ctrl: ctrl}
	mock.recorder = &MockGetSuperAdminListUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetSuperAdminListUseCase) EXPECT() *MockGetSuperAdminListUseCaseMockRecorder {
	return m.recorder
}

// GetSuperAdminList mocks base method.
func (m *MockGetSuperAdminListUseCase) GetSuperAdminList(cmd user.GetSuperAdminListCommand) ([]user.User, uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSuperAdminList", cmd)
	ret0, _ := ret[0].([]user.User)
	ret1, _ := ret[1].(uint)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSuperAdminList indicates an expected call of GetSuperAdminList.
func (mr *MockGetSuperAdminListUseCaseMockRecorder) GetSuperAdminList(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSuperAdminList", reflect.TypeOf((*MockGetSuperAdminListUseCase)(nil).GetSuperAdminList), cmd)
}
