// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/user (interfaces: DeleteTenantUserUseCase,DeleteTenantAdminUseCase,DeleteSuperAdminUseCase)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/user/mocks/use_cases_delete.go -package=mocks . DeleteTenantUserUseCase,DeleteTenantAdminUseCase,DeleteSuperAdminUseCase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	user "backend/internal/user"

	gomock "go.uber.org/mock/gomock"
)

// MockDeleteTenantUserUseCase is a mock of DeleteTenantUserUseCase interface.
type MockDeleteTenantUserUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteTenantUserUseCaseMockRecorder
	isgomock struct{}
}

// MockDeleteTenantUserUseCaseMockRecorder is the mock recorder for MockDeleteTenantUserUseCase.
type MockDeleteTenantUserUseCaseMockRecorder struct {
	mock *MockDeleteTenantUserUseCase
}

// NewMockDeleteTenantUserUseCase creates a new mock instance.
func NewMockDeleteTenantUserUseCase(ctrl *gomock.Controller) *MockDeleteTenantUserUseCase {
	mock := &MockDeleteTenantUserUseCase{ctrl: ctrl}
	mock.recorder = &MockDeleteTenantUserUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteTenantUserUseCase) EXPECT() *MockDeleteTenantUserUseCaseMockRecorder {
	return m.recorder
}

// DeleteTenantUser mocks base method.
func (m *MockDeleteTenantUserUseCase) DeleteTenantUser(cmd user.DeleteTenantUserCommand) (user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTenantUser", cmd)
	ret0, _ := ret[0].(user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTenantUser indicates an expected call of DeleteTenantUser.
func (mr *MockDeleteTenantUserUseCaseMockRecorder) DeleteTenantUser(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTenantUser", reflect.TypeOf((*MockDeleteTenantUserUseCase)(nil).DeleteTenantUser), cmd)
}

// MockDeleteTenantAdminUseCase is a mock of DeleteTenantAdminUseCase interface.
type MockDeleteTenantAdminUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteTenantAdminUseCaseMockRecorder
	isgomock struct{}
}

// MockDeleteTenantAdminUseCaseMockRecorder is the mock recorder for MockDeleteTenantAdminUseCase.
type MockDeleteTenantAdminUseCaseMockRecorder struct {
	mock *MockDeleteTenantAdminUseCase
}

// NewMockDeleteTenantAdminUseCase creates a new mock instance.
func NewMockDeleteTenantAdminUseCase(ctrl *gomock.Controller) *MockDeleteTenantAdminUseCase {
	mock := &MockDeleteTenantAdminUseCase{ctrl: ctrl}
	mock.recorder = &MockDeleteTenantAdminUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteTenantAdminUseCase) EXPECT() *MockDeleteTenantAdminUseCaseMockRecorder {
	return m.recorder
}

// DeleteTenantAdmin mocks base method.
func (m *MockDeleteTenantAdminUseCase) DeleteTenantAdmin(cmd user.DeleteTenantAdminCommand) (user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTenantAdmin", cmd)
	ret0, _ := ret[0].(user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTenantAdmin indicates an expected call of DeleteTenantAdmin.
func (mr *MockDeleteTenantAdminUseCaseMockRecorder) DeleteTenantAdmin(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTenantAdmin", reflect.TypeOf((*MockDeleteTenantAdminUseCase)(nil).DeleteTenantAdmin), cmd)
}

// MockDeleteSuperAdminUseCase is a mock of DeleteSuperAdminUseCase interface.
type MockDeleteSuperAdminUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteSuperAdminUseCaseMockRecorder
	isgomock struct{}
}

// MockDeleteSuperAdminUseCaseMockRecorder is the mock recorder for MockDeleteSuperAdminUseCase.
type MockDeleteSuperAdminUseCaseMockRecorder struct {
	mock *MockDeleteSuperAdminUseCase
}

// NewMockDeleteSuperAdminUseCase creates a new mock instance.
func NewMockDeleteSuperAdminUseCase(ctrl *gomock.Controller) *MockDeleteSuperAdminUseCase {
	mock := &MockDeleteSuperAdminUseCase{ctrl: ctrl}
	mock.recorder = &MockDeleteSuperAdminUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteSuperAdminUseCase) EXPECT() *MockDeleteSuperAdminUseCaseMockRecorder {
	return m.recorder
}

// DeleteSuperAdmin mocks base method.
func (m *MockDeleteSuperAdminUseCase) DeleteSuperAdmin(cmd user.DeleteSuperAdminCommand) (user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSuperAdmin", cmd)
	ret0, _ := ret[0].(user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteSuperAdmin indicates an expected call of DeleteSuperAdmin.
func (mr *MockDeleteSuperAdminUseCaseMockRecorder) DeleteSuperAdmin(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSuperAdmin", reflect.TypeOf((*MockDeleteSuperAdminUseCase)(nil).DeleteSuperAdmin), cmd)
}
