// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/user (interfaces: CreateTenantUserUseCase,CreateTenantAdminUseCase,CreateSuperAdminUseCase)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/user/mocks/use_cases_create.go -package=mocks . CreateTenantUserUseCase,CreateTenantAdminUseCase,CreateSuperAdminUseCase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	user "backend/internal/user"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCreateTenantUserUseCase is a mock of CreateTenantUserUseCase interface.
type MockCreateTenantUserUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCreateTenantUserUseCaseMockRecorder
	isgomock struct{}
}

// MockCreateTenantUserUseCaseMockRecorder is the mock recorder for MockCreateTenantUserUseCase.
type MockCreateTenantUserUseCaseMockRecorder struct {
	mock *MockCreateTenantUserUseCase
}

// NewMockCreateTenantUserUseCase creates a new mock instance.
func NewMockCreateTenantUserUseCase(ctrl *gomock.Controller) *MockCreateTenantUserUseCase {
	mock := &MockCreateTenantUserUseCase{ctrl: ctrl}
	mock.recorder = &MockCreateTenantUserUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateTenantUserUseCase) EXPECT() *MockCreateTenantUserUseCaseMockRecorder {
	return m.recorder
}

// CreateTenantUser mocks base method.
func (m *MockCreateTenantUserUseCase) CreateTenantUser(cmd user.CreateTenantUserCommand) (user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTenantUser", cmd)
	ret0, _ := ret[0].(user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTenantUser indicates an expected call of CreateTenantUser.
func (mr *MockCreateTenantUserUseCaseMockRecorder) CreateTenantUser(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTenantUser", reflect.TypeOf((*MockCreateTenantUserUseCase)(nil).CreateTenantUser), cmd)
}

// MockCreateTenantAdminUseCase is a mock of CreateTenantAdminUseCase interface.
type MockCreateTenantAdminUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCreateTenantAdminUseCaseMockRecorder
	isgomock struct{}
}

// MockCreateTenantAdminUseCaseMockRecorder is the mock recorder for MockCreateTenantAdminUseCase.
type MockCreateTenantAdminUseCaseMockRecorder struct {
	mock *MockCreateTenantAdminUseCase
}

// NewMockCreateTenantAdminUseCase creates a new mock instance.
func NewMockCreateTenantAdminUseCase(ctrl *gomock.Controller) *MockCreateTenantAdminUseCase {
	mock := &MockCreateTenantAdminUseCase{ctrl: ctrl}
	mock.recorder = &MockCreateTenantAdminUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateTenantAdminUseCase) EXPECT() *MockCreateTenantAdminUseCaseMockRecorder {
	return m.recorder
}

// CreateTenantAdmin mocks base method.
func (m *MockCreateTenantAdminUseCase) CreateTenantAdmin(cmd user.CreateTenantAdminCommand) (user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTenantAdmin", cmd)
	ret0, _ := ret[0].(user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTenantAdmin indicates an expected call of CreateTenantAdmin.
func (mr *MockCreateTenantAdminUseCaseMockRecorder) CreateTenantAdmin(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTenantAdmin", reflect.TypeOf((*MockCreateTenantAdminUseCase)(nil).CreateTenantAdmin), cmd)
}

// MockCreateSuperAdminUseCase is a mock of CreateSuperAdminUseCase interface.
type MockCreateSuperAdminUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCreateSuperAdminUseCaseMockRecorder
	isgomock struct{}
}

// MockCreateSuperAdminUseCaseMockRecorder is the mock recorder for MockCreateSuperAdminUseCase.
type MockCreateSuperAdminUseCaseMockRecorder struct {
	mock *MockCreateSuperAdminUseCase
}

// NewMockCreateSuperAdminUseCase creates a new mock instance.
func NewMockCreateSuperAdminUseCase(ctrl *gomock.Controller) *MockCreateSuperAdminUseCase {
	mock := &MockCreateSuperAdminUseCase{ctrl: ctrl}
	mock.recorder = &MockCreateSuperAdminUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateSuperAdminUseCase) EXPECT() *MockCreateSuperAdminUseCaseMockRecorder {
	return m.recorder
}

// CreateSuperAdmin mocks base method.
func (m *MockCreateSuperAdminUseCase) CreateSuperAdmin(cmd user.CreateSuperAdminCommand) (user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSuperAdmin", cmd)
	ret0, _ := ret[0].(user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSuperAdmin indicates an expected call of CreateSuperAdmin.
func (mr *MockCreateSuperAdminUseCaseMockRecorder) CreateSuperAdmin(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSuperAdmin", reflect.TypeOf((*MockCreateSuperAdminUseCase)(nil).CreateSuperAdmin), cmd)
}
