// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/real_time_data (interfaces: RealTimeDataNATSReader)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/real_time_data/mocks/nats_reader.go -package=mocks . RealTimeDataNATSReader
//

// Package mocks is a generated GoMock package.
package mocks

import (
	real_time_data "backend/internal/real_time_data"
	profile "backend/internal/sensor/profile"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRealTimeDataNATSReader is a mock of RealTimeDataNATSReader interface.
type MockRealTimeDataNATSReader struct {
	ctrl     *gomock.Controller
	recorder *MockRealTimeDataNATSReaderMockRecorder
	isgomock struct{}
}

// MockRealTimeDataNATSReaderMockRecorder is the mock recorder for MockRealTimeDataNATSReader.
type MockRealTimeDataNATSReaderMockRecorder struct {
	mock *MockRealTimeDataNATSReader
}

// NewMockRealTimeDataNATSReader creates a new mock instance.
func NewMockRealTimeDataNATSReader(ctrl *gomock.Controller) *MockRealTimeDataNATSReader {
	mock := &MockRealTimeDataNATSReader{ctrl: ctrl}
	mock.recorder = &MockRealTimeDataNATSReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRealTimeDataNATSReader) EXPECT() *MockRealTimeDataNATSReaderMockRecorder {
	return m.recorder
}

// StartSubscriber mocks base method.
func (m *MockRealTimeDataNATSReader) StartSubscriber(subject string, arg1 profile.SensorProfile, receivingChannel chan real_time_data.RealTimeSample, errorChannel chan real_time_data.RealTimeError) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartSubscriber", subject, arg1, receivingChannel, errorChannel)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartSubscriber indicates an expected call of StartSubscriber.
func (mr *MockRealTimeDataNATSReaderMockRecorder) StartSubscriber(subject, arg1, receivingChannel, errorChannel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartSubscriber", reflect.TypeOf((*MockRealTimeDataNATSReader)(nil).StartSubscriber), subject, arg1, receivingChannel, errorChannel)
}
