// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/real_time_data (interfaces: RealTimeDataPort)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/real_time_data/mocks/ports.go -package=mocks . RealTimeDataPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	real_time_data "backend/internal/real_time_data"
	sensor "backend/internal/sensor"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRealTimeDataPort is a mock of RealTimeDataPort interface.
type MockRealTimeDataPort struct {
	ctrl     *gomock.Controller
	recorder *MockRealTimeDataPortMockRecorder
	isgomock struct{}
}

// MockRealTimeDataPortMockRecorder is the mock recorder for MockRealTimeDataPort.
type MockRealTimeDataPortMockRecorder struct {
	mock *MockRealTimeDataPort
}

// NewMockRealTimeDataPort creates a new mock instance.
func NewMockRealTimeDataPort(ctrl *gomock.Controller) *MockRealTimeDataPort {
	mock := &MockRealTimeDataPort{ctrl: ctrl}
	mock.recorder = &MockRealTimeDataPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRealTimeDataPort) EXPECT() *MockRealTimeDataPortMockRecorder {
	return m.recorder
}

// StartDataRetriever mocks base method.
func (m *MockRealTimeDataPort) StartDataRetriever(tenantId uuid.UUID, arg1 sensor.Sensor, dataChan chan real_time_data.RealTimeSample, errorChan chan real_time_data.RealTimeError) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartDataRetriever", tenantId, arg1, dataChan, errorChan)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartDataRetriever indicates an expected call of StartDataRetriever.
func (mr *MockRealTimeDataPortMockRecorder) StartDataRetriever(tenantId, arg1, dataChan, errorChan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartDataRetriever", reflect.TypeOf((*MockRealTimeDataPort)(nil).StartDataRetriever), tenantId, arg1, dataChan, errorChan)
}
