// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/real_time_data (interfaces: GetRealTimeDataUseCase)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/real_time_data/mocks/use_case.go -package=mocks . GetRealTimeDataUseCase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	real_time_data "backend/internal/real_time_data"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGetRealTimeDataUseCase is a mock of GetRealTimeDataUseCase interface.
type MockGetRealTimeDataUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetRealTimeDataUseCaseMockRecorder
	isgomock struct{}
}

// MockGetRealTimeDataUseCaseMockRecorder is the mock recorder for MockGetRealTimeDataUseCase.
type MockGetRealTimeDataUseCaseMockRecorder struct {
	mock *MockGetRealTimeDataUseCase
}

// NewMockGetRealTimeDataUseCase creates a new mock instance.
func NewMockGetRealTimeDataUseCase(ctrl *gomock.Controller) *MockGetRealTimeDataUseCase {
	mock := &MockGetRealTimeDataUseCase{ctrl: ctrl}
	mock.recorder = &MockGetRealTimeDataUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetRealTimeDataUseCase) EXPECT() *MockGetRealTimeDataUseCaseMockRecorder {
	return m.recorder
}

// GetRealTimeData mocks base method.
func (m *MockGetRealTimeDataUseCase) GetRealTimeData(cmd real_time_data.GetRealTimeDataCommand) (chan real_time_data.RealTimeSample, chan real_time_data.RealTimeError, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRealTimeData", cmd)
	ret0, _ := ret[0].(chan real_time_data.RealTimeSample)
	ret1, _ := ret[1].(chan real_time_data.RealTimeError)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetRealTimeData indicates an expected call of GetRealTimeData.
func (mr *MockGetRealTimeDataUseCaseMockRecorder) GetRealTimeData(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRealTimeData", reflect.TypeOf((*MockGetRealTimeDataUseCase)(nil).GetRealTimeData), cmd)
}
