// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/sensor (interfaces: DatabaseRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/sensor/mocks/database_repository.go -package=mocks . DatabaseRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	sensor "backend/internal/sensor"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDatabaseRepository is a mock of DatabaseRepository interface.
type MockDatabaseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseRepositoryMockRecorder
	isgomock struct{}
}

// MockDatabaseRepositoryMockRecorder is the mock recorder for MockDatabaseRepository.
type MockDatabaseRepositoryMockRecorder struct {
	mock *MockDatabaseRepository
}

// NewMockDatabaseRepository creates a new mock instance.
func NewMockDatabaseRepository(ctrl *gomock.Controller) *MockDatabaseRepository {
	mock := &MockDatabaseRepository{ctrl: ctrl}
	mock.recorder = &MockDatabaseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabaseRepository) EXPECT() *MockDatabaseRepositoryMockRecorder {
	return m.recorder
}

// CreateSensor mocks base method.
func (m *MockDatabaseRepository) CreateSensor(entity *sensor.SensorEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSensor", entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSensor indicates an expected call of CreateSensor.
func (mr *MockDatabaseRepositoryMockRecorder) CreateSensor(entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSensor", reflect.TypeOf((*MockDatabaseRepository)(nil).CreateSensor), entity)
}

// DeleteSensor mocks base method.
func (m *MockDatabaseRepository) DeleteSensor(entity *sensor.SensorEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSensor", entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSensor indicates an expected call of DeleteSensor.
func (mr *MockDatabaseRepositoryMockRecorder) DeleteSensor(entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSensor", reflect.TypeOf((*MockDatabaseRepository)(nil).DeleteSensor), entity)
}

// GetSensorById mocks base method.
func (m *MockDatabaseRepository) GetSensorById(sensorId string) (sensor.SensorEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSensorById", sensorId)
	ret0, _ := ret[0].(sensor.SensorEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSensorById indicates an expected call of GetSensorById.
func (mr *MockDatabaseRepositoryMockRecorder) GetSensorById(sensorId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSensorById", reflect.TypeOf((*MockDatabaseRepository)(nil).GetSensorById), sensorId)
}

// GetSensorByTenant mocks base method.
func (m *MockDatabaseRepository) GetSensorByTenant(tenantId, sensorId string) (sensor.SensorEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSensorByTenant", tenantId, sensorId)
	ret0, _ := ret[0].(sensor.SensorEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSensorByTenant indicates an expected call of GetSensorByTenant.
func (mr *MockDatabaseRepositoryMockRecorder) GetSensorByTenant(tenantId, sensorId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSensorByTenant", reflect.TypeOf((*MockDatabaseRepository)(nil).GetSensorByTenant), tenantId, sensorId)
}

// GetSensorWithGateway mocks base method.
func (m *MockDatabaseRepository) GetSensorWithGateway(sensorId string) (sensor.SensorEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSensorWithGateway", sensorId)
	ret0, _ := ret[0].(sensor.SensorEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSensorWithGateway indicates an expected call of GetSensorWithGateway.
func (mr *MockDatabaseRepositoryMockRecorder) GetSensorWithGateway(sensorId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSensorWithGateway", reflect.TypeOf((*MockDatabaseRepository)(nil).GetSensorWithGateway), sensorId)
}

// GetSensorsByGatewayId mocks base method.
func (m *MockDatabaseRepository) GetSensorsByGatewayId(gatewayId string, offset, limit int) ([]sensor.SensorEntity, uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSensorsByGatewayId", gatewayId, offset, limit)
	ret0, _ := ret[0].([]sensor.SensorEntity)
	ret1, _ := ret[1].(uint)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSensorsByGatewayId indicates an expected call of GetSensorsByGatewayId.
func (mr *MockDatabaseRepositoryMockRecorder) GetSensorsByGatewayId(gatewayId, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSensorsByGatewayId", reflect.TypeOf((*MockDatabaseRepository)(nil).GetSensorsByGatewayId), gatewayId, offset, limit)
}

// GetSensorsByTenantId mocks base method.
func (m *MockDatabaseRepository) GetSensorsByTenantId(tenantId string, offset, limit int) ([]sensor.SensorEntity, uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSensorsByTenantId", tenantId, offset, limit)
	ret0, _ := ret[0].([]sensor.SensorEntity)
	ret1, _ := ret[1].(uint)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSensorsByTenantId indicates an expected call of GetSensorsByTenantId.
func (mr *MockDatabaseRepositoryMockRecorder) GetSensorsByTenantId(tenantId, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSensorsByTenantId", reflect.TypeOf((*MockDatabaseRepository)(nil).GetSensorsByTenantId), tenantId, offset, limit)
}

// UpdateSensor mocks base method.
func (m *MockDatabaseRepository) UpdateSensor(sensorId, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSensor", sensorId, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSensor indicates an expected call of UpdateSensor.
func (mr *MockDatabaseRepositoryMockRecorder) UpdateSensor(sensorId, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSensor", reflect.TypeOf((*MockDatabaseRepository)(nil).UpdateSensor), sensorId, status)
}
