// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/sensor (interfaces: MessageBrokerRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/sensor/mocks/message_broker_repository.go -package=mocks . MessageBrokerRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	sensor "backend/internal/sensor"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMessageBrokerRepository is a mock of MessageBrokerRepository interface.
type MockMessageBrokerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMessageBrokerRepositoryMockRecorder
	isgomock struct{}
}

// MockMessageBrokerRepositoryMockRecorder is the mock recorder for MockMessageBrokerRepository.
type MockMessageBrokerRepositoryMockRecorder struct {
	mock *MockMessageBrokerRepository
}

// NewMockMessageBrokerRepository creates a new mock instance.
func NewMockMessageBrokerRepository(ctrl *gomock.Controller) *MockMessageBrokerRepository {
	mock := &MockMessageBrokerRepository{ctrl: ctrl}
	mock.recorder = &MockMessageBrokerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageBrokerRepository) EXPECT() *MockMessageBrokerRepositoryMockRecorder {
	return m.recorder
}

// SendCreateSensorCmd mocks base method.
func (m *MockMessageBrokerRepository) SendCreateSensorCmd(cmd *sensor.CreateSensorCmdEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendCreateSensorCmd", cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendCreateSensorCmd indicates an expected call of SendCreateSensorCmd.
func (mr *MockMessageBrokerRepositoryMockRecorder) SendCreateSensorCmd(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendCreateSensorCmd", reflect.TypeOf((*MockMessageBrokerRepository)(nil).SendCreateSensorCmd), cmd)
}

// SendDeleteSensorCmd mocks base method.
func (m *MockMessageBrokerRepository) SendDeleteSensorCmd(cmd *sensor.DeleteSensorCmdEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendDeleteSensorCmd", cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendDeleteSensorCmd indicates an expected call of SendDeleteSensorCmd.
func (mr *MockMessageBrokerRepositoryMockRecorder) SendDeleteSensorCmd(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendDeleteSensorCmd", reflect.TypeOf((*MockMessageBrokerRepository)(nil).SendDeleteSensorCmd), cmd)
}

// SendInterruptSensorCmd mocks base method.
func (m *MockMessageBrokerRepository) SendInterruptSensorCmd(cmd *sensor.InterruptSensorCmdEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendInterruptSensorCmd", cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendInterruptSensorCmd indicates an expected call of SendInterruptSensorCmd.
func (mr *MockMessageBrokerRepositoryMockRecorder) SendInterruptSensorCmd(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendInterruptSensorCmd", reflect.TypeOf((*MockMessageBrokerRepository)(nil).SendInterruptSensorCmd), cmd)
}

// SendResumeSensorCmd mocks base method.
func (m *MockMessageBrokerRepository) SendResumeSensorCmd(cmd *sensor.ResumeSensorCmdEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendResumeSensorCmd", cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendResumeSensorCmd indicates an expected call of SendResumeSensorCmd.
func (mr *MockMessageBrokerRepositoryMockRecorder) SendResumeSensorCmd(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendResumeSensorCmd", reflect.TypeOf((*MockMessageBrokerRepository)(nil).SendResumeSensorCmd), cmd)
}
