// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/sensor (interfaces: GetSensorByTenantPort)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/sensor/mocks/ports_getters.go -package=mocks . GetSensorByTenantPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	sensor "backend/internal/sensor"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockGetSensorByTenantPort is a mock of GetSensorByTenantPort interface.
type MockGetSensorByTenantPort struct {
	ctrl     *gomock.Controller
	recorder *MockGetSensorByTenantPortMockRecorder
	isgomock struct{}
}

// MockGetSensorByTenantPortMockRecorder is the mock recorder for MockGetSensorByTenantPort.
type MockGetSensorByTenantPortMockRecorder struct {
	mock *MockGetSensorByTenantPort
}

// NewMockGetSensorByTenantPort creates a new mock instance.
func NewMockGetSensorByTenantPort(ctrl *gomock.Controller) *MockGetSensorByTenantPort {
	mock := &MockGetSensorByTenantPort{ctrl: ctrl}
	mock.recorder = &MockGetSensorByTenantPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetSensorByTenantPort) EXPECT() *MockGetSensorByTenantPortMockRecorder {
	return m.recorder
}

// GetSensorByTenant mocks base method.
func (m *MockGetSensorByTenantPort) GetSensorByTenant(tenantId, sensorId uuid.UUID) (sensor.Sensor, *uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSensorByTenant", tenantId, sensorId)
	ret0, _ := ret[0].(sensor.Sensor)
	ret1, _ := ret[1].(*uuid.UUID)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSensorByTenant indicates an expected call of GetSensorByTenant.
func (mr *MockGetSensorByTenantPortMockRecorder) GetSensorByTenant(tenantId, sensorId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSensorByTenant", reflect.TypeOf((*MockGetSensorByTenantPort)(nil).GetSensorByTenant), tenantId, sensorId)
}
