// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/sensor (interfaces: GetSensorByIdPort)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/sensor/mocks/port_getById.go -package=mocks . GetSensorByIdPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	sensor "backend/internal/sensor"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockGetSensorByIdPort is a mock of GetSensorByIdPort interface.
type MockGetSensorByIdPort struct {
	ctrl     *gomock.Controller
	recorder *MockGetSensorByIdPortMockRecorder
	isgomock struct{}
}

// MockGetSensorByIdPortMockRecorder is the mock recorder for MockGetSensorByIdPort.
type MockGetSensorByIdPortMockRecorder struct {
	mock *MockGetSensorByIdPort
}

// NewMockGetSensorByIdPort creates a new mock instance.
func NewMockGetSensorByIdPort(ctrl *gomock.Controller) *MockGetSensorByIdPort {
	mock := &MockGetSensorByIdPort{ctrl: ctrl}
	mock.recorder = &MockGetSensorByIdPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetSensorByIdPort) EXPECT() *MockGetSensorByIdPortMockRecorder {
	return m.recorder
}

// GetSensorById mocks base method.
func (m *MockGetSensorByIdPort) GetSensorById(sensorId uuid.UUID) (sensor.Sensor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSensorById", sensorId)
	ret0, _ := ret[0].(sensor.Sensor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSensorById indicates an expected call of GetSensorById.
func (mr *MockGetSensorByIdPortMockRecorder) GetSensorById(sensorId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSensorById", reflect.TypeOf((*MockGetSensorByIdPort)(nil).GetSensorById), sensorId)
}
