// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/sensor (interfaces: SendInterruptCmdPort,SendResumeCmdPort,UpdateSensorStatusPort)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/sensor/mocks/port_interrupt_resume.go -package=mocks . SendInterruptCmdPort,SendResumeCmdPort,UpdateSensorStatusPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	sensor "backend/internal/sensor"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockSendInterruptCmdPort is a mock of SendInterruptCmdPort interface.
type MockSendInterruptCmdPort struct {
	ctrl     *gomock.Controller
	recorder *MockSendInterruptCmdPortMockRecorder
	isgomock struct{}
}

// MockSendInterruptCmdPortMockRecorder is the mock recorder for MockSendInterruptCmdPort.
type MockSendInterruptCmdPortMockRecorder struct {
	mock *MockSendInterruptCmdPort
}

// NewMockSendInterruptCmdPort creates a new mock instance.
func NewMockSendInterruptCmdPort(ctrl *gomock.Controller) *MockSendInterruptCmdPort {
	mock := &MockSendInterruptCmdPort{ctrl: ctrl}
	mock.recorder = &MockSendInterruptCmdPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSendInterruptCmdPort) EXPECT() *MockSendInterruptCmdPortMockRecorder {
	return m.recorder
}

// SendInterrupt mocks base method.
func (m *MockSendInterruptCmdPort) SendInterrupt(sensorId, gatewayId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendInterrupt", sensorId, gatewayId)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendInterrupt indicates an expected call of SendInterrupt.
func (mr *MockSendInterruptCmdPortMockRecorder) SendInterrupt(sensorId, gatewayId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendInterrupt", reflect.TypeOf((*MockSendInterruptCmdPort)(nil).SendInterrupt), sensorId, gatewayId)
}

// MockSendResumeCmdPort is a mock of SendResumeCmdPort interface.
type MockSendResumeCmdPort struct {
	ctrl     *gomock.Controller
	recorder *MockSendResumeCmdPortMockRecorder
	isgomock struct{}
}

// MockSendResumeCmdPortMockRecorder is the mock recorder for MockSendResumeCmdPort.
type MockSendResumeCmdPortMockRecorder struct {
	mock *MockSendResumeCmdPort
}

// NewMockSendResumeCmdPort creates a new mock instance.
func NewMockSendResumeCmdPort(ctrl *gomock.Controller) *MockSendResumeCmdPort {
	mock := &MockSendResumeCmdPort{ctrl: ctrl}
	mock.recorder = &MockSendResumeCmdPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSendResumeCmdPort) EXPECT() *MockSendResumeCmdPortMockRecorder {
	return m.recorder
}

// SendResume mocks base method.
func (m *MockSendResumeCmdPort) SendResume(sensorId, gatewayId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendResume", sensorId, gatewayId)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendResume indicates an expected call of SendResume.
func (mr *MockSendResumeCmdPortMockRecorder) SendResume(sensorId, gatewayId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendResume", reflect.TypeOf((*MockSendResumeCmdPort)(nil).SendResume), sensorId, gatewayId)
}

// MockUpdateSensorStatusPort is a mock of UpdateSensorStatusPort interface.
type MockUpdateSensorStatusPort struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateSensorStatusPortMockRecorder
	isgomock struct{}
}

// MockUpdateSensorStatusPortMockRecorder is the mock recorder for MockUpdateSensorStatusPort.
type MockUpdateSensorStatusPortMockRecorder struct {
	mock *MockUpdateSensorStatusPort
}

// NewMockUpdateSensorStatusPort creates a new mock instance.
func NewMockUpdateSensorStatusPort(ctrl *gomock.Controller) *MockUpdateSensorStatusPort {
	mock := &MockUpdateSensorStatusPort{ctrl: ctrl}
	mock.recorder = &MockUpdateSensorStatusPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateSensorStatusPort) EXPECT() *MockUpdateSensorStatusPortMockRecorder {
	return m.recorder
}

// UpdateSensorStatus mocks base method.
func (m *MockUpdateSensorStatusPort) UpdateSensorStatus(arg0 sensor.Sensor, status sensor.SensorStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSensorStatus", arg0, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSensorStatus indicates an expected call of UpdateSensorStatus.
func (mr *MockUpdateSensorStatusPortMockRecorder) UpdateSensorStatus(arg0, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSensorStatus", reflect.TypeOf((*MockUpdateSensorStatusPort)(nil).UpdateSensorStatus), arg0, status)
}
