// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/sensor (interfaces: DeleteSensorPort,DeleteSensorCmdPort)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/sensor/mocks/port_delete.go -package=mocks . DeleteSensorPort,DeleteSensorCmdPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	sensor "backend/internal/sensor"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockDeleteSensorPort is a mock of DeleteSensorPort interface.
type MockDeleteSensorPort struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteSensorPortMockRecorder
	isgomock struct{}
}

// MockDeleteSensorPortMockRecorder is the mock recorder for MockDeleteSensorPort.
type MockDeleteSensorPortMockRecorder struct {
	mock *MockDeleteSensorPort
}

// NewMockDeleteSensorPort creates a new mock instance.
func NewMockDeleteSensorPort(ctrl *gomock.Controller) *MockDeleteSensorPort {
	mock := &MockDeleteSensorPort{ctrl: ctrl}
	mock.recorder = &MockDeleteSensorPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteSensorPort) EXPECT() *MockDeleteSensorPortMockRecorder {
	return m.recorder
}

// DeleteSensor mocks base method.
func (m *MockDeleteSensorPort) DeleteSensor(sensorId uuid.UUID) (sensor.Sensor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSensor", sensorId)
	ret0, _ := ret[0].(sensor.Sensor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteSensor indicates an expected call of DeleteSensor.
func (mr *MockDeleteSensorPortMockRecorder) DeleteSensor(sensorId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSensor", reflect.TypeOf((*MockDeleteSensorPort)(nil).DeleteSensor), sensorId)
}

// MockDeleteSensorCmdPort is a mock of DeleteSensorCmdPort interface.
type MockDeleteSensorCmdPort struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteSensorCmdPortMockRecorder
	isgomock struct{}
}

// MockDeleteSensorCmdPortMockRecorder is the mock recorder for MockDeleteSensorCmdPort.
type MockDeleteSensorCmdPortMockRecorder struct {
	mock *MockDeleteSensorCmdPort
}

// NewMockDeleteSensorCmdPort creates a new mock instance.
func NewMockDeleteSensorCmdPort(ctrl *gomock.Controller) *MockDeleteSensorCmdPort {
	mock := &MockDeleteSensorCmdPort{ctrl: ctrl}
	mock.recorder = &MockDeleteSensorCmdPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteSensorCmdPort) EXPECT() *MockDeleteSensorCmdPortMockRecorder {
	return m.recorder
}

// SendDeleteSensorCmd mocks base method.
func (m *MockDeleteSensorCmdPort) SendDeleteSensorCmd(sensord, gatewayId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendDeleteSensorCmd", sensord, gatewayId)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendDeleteSensorCmd indicates an expected call of SendDeleteSensorCmd.
func (mr *MockDeleteSensorCmdPortMockRecorder) SendDeleteSensorCmd(sensord, gatewayId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendDeleteSensorCmd", reflect.TypeOf((*MockDeleteSensorCmdPort)(nil).SendDeleteSensorCmd), sensord, gatewayId)
}
