// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/sensor (interfaces: CreateSensorPort,CreateSensorCmdPort)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/sensor/mocks/port_create.go -package=mocks . CreateSensorPort,CreateSensorCmdPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	sensor "backend/internal/sensor"
	profile "backend/internal/sensor/profile"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCreateSensorPort is a mock of CreateSensorPort interface.
type MockCreateSensorPort struct {
	ctrl     *gomock.Controller
	recorder *MockCreateSensorPortMockRecorder
	isgomock struct{}
}

// MockCreateSensorPortMockRecorder is the mock recorder for MockCreateSensorPort.
type MockCreateSensorPortMockRecorder struct {
	mock *MockCreateSensorPort
}

// NewMockCreateSensorPort creates a new mock instance.
func NewMockCreateSensorPort(ctrl *gomock.Controller) *MockCreateSensorPort {
	mock := &MockCreateSensorPort{ctrl: ctrl}
	mock.recorder = &MockCreateSensorPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateSensorPort) EXPECT() *MockCreateSensorPortMockRecorder {
	return m.recorder
}

// CreateSensor mocks base method.
func (m *MockCreateSensorPort) CreateSensor(sensorId, gatewayId uuid.UUID, name string, interval time.Duration, arg4 profile.SensorProfile) (sensor.Sensor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSensor", sensorId, gatewayId, name, interval, arg4)
	ret0, _ := ret[0].(sensor.Sensor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSensor indicates an expected call of CreateSensor.
func (mr *MockCreateSensorPortMockRecorder) CreateSensor(sensorId, gatewayId, name, interval, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSensor", reflect.TypeOf((*MockCreateSensorPort)(nil).CreateSensor), sensorId, gatewayId, name, interval, arg4)
}

// MockCreateSensorCmdPort is a mock of CreateSensorCmdPort interface.
type MockCreateSensorCmdPort struct {
	ctrl     *gomock.Controller
	recorder *MockCreateSensorCmdPortMockRecorder
	isgomock struct{}
}

// MockCreateSensorCmdPortMockRecorder is the mock recorder for MockCreateSensorCmdPort.
type MockCreateSensorCmdPortMockRecorder struct {
	mock *MockCreateSensorCmdPort
}

// NewMockCreateSensorCmdPort creates a new mock instance.
func NewMockCreateSensorCmdPort(ctrl *gomock.Controller) *MockCreateSensorCmdPort {
	mock := &MockCreateSensorCmdPort{ctrl: ctrl}
	mock.recorder = &MockCreateSensorCmdPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateSensorCmdPort) EXPECT() *MockCreateSensorCmdPortMockRecorder {
	return m.recorder
}

// SendCreateSensorCmd mocks base method.
func (m *MockCreateSensorCmdPort) SendCreateSensorCmd(sensord, gatewayId uuid.UUID, interval time.Duration, arg3 profile.SensorProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendCreateSensorCmd", sensord, gatewayId, interval, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendCreateSensorCmd indicates an expected call of SendCreateSensorCmd.
func (mr *MockCreateSensorCmdPortMockRecorder) SendCreateSensorCmd(sensord, gatewayId, interval, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendCreateSensorCmd", reflect.TypeOf((*MockCreateSensorCmdPort)(nil).SendCreateSensorCmd), sensord, gatewayId, interval, arg3)
}
