// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/sensor (interfaces: GetSensorsByTenantIdPort)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/sensor/mocks/port_getByTenantId.go -package=mocks . GetSensorsByTenantIdPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	sensor "backend/internal/sensor"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockGetSensorsByTenantIdPort is a mock of GetSensorsByTenantIdPort interface.
type MockGetSensorsByTenantIdPort struct {
	ctrl     *gomock.Controller
	recorder *MockGetSensorsByTenantIdPortMockRecorder
	isgomock struct{}
}

// MockGetSensorsByTenantIdPortMockRecorder is the mock recorder for MockGetSensorsByTenantIdPort.
type MockGetSensorsByTenantIdPortMockRecorder struct {
	mock *MockGetSensorsByTenantIdPort
}

// NewMockGetSensorsByTenantIdPort creates a new mock instance.
func NewMockGetSensorsByTenantIdPort(ctrl *gomock.Controller) *MockGetSensorsByTenantIdPort {
	mock := &MockGetSensorsByTenantIdPort{ctrl: ctrl}
	mock.recorder = &MockGetSensorsByTenantIdPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetSensorsByTenantIdPort) EXPECT() *MockGetSensorsByTenantIdPortMockRecorder {
	return m.recorder
}

// GetSensorsByTenant mocks base method.
func (m *MockGetSensorsByTenantIdPort) GetSensorsByTenant(tenantId uuid.UUID, page, limit int) ([]sensor.Sensor, uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSensorsByTenant", tenantId, page, limit)
	ret0, _ := ret[0].([]sensor.Sensor)
	ret1, _ := ret[1].(uint)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSensorsByTenant indicates an expected call of GetSensorsByTenant.
func (mr *MockGetSensorsByTenantIdPortMockRecorder) GetSensorsByTenant(tenantId, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSensorsByTenant", reflect.TypeOf((*MockGetSensorsByTenantIdPort)(nil).GetSensorsByTenant), tenantId, page, limit)
}
