// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/sensor (interfaces: GetSensorsByGatewayIdPort)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/sensor/mocks/port_getByGatewayId.go -package=mocks . GetSensorsByGatewayIdPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	sensor "backend/internal/sensor"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockGetSensorsByGatewayIdPort is a mock of GetSensorsByGatewayIdPort interface.
type MockGetSensorsByGatewayIdPort struct {
	ctrl     *gomock.Controller
	recorder *MockGetSensorsByGatewayIdPortMockRecorder
	isgomock struct{}
}

// MockGetSensorsByGatewayIdPortMockRecorder is the mock recorder for MockGetSensorsByGatewayIdPort.
type MockGetSensorsByGatewayIdPortMockRecorder struct {
	mock *MockGetSensorsByGatewayIdPort
}

// NewMockGetSensorsByGatewayIdPort creates a new mock instance.
func NewMockGetSensorsByGatewayIdPort(ctrl *gomock.Controller) *MockGetSensorsByGatewayIdPort {
	mock := &MockGetSensorsByGatewayIdPort{ctrl: ctrl}
	mock.recorder = &MockGetSensorsByGatewayIdPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetSensorsByGatewayIdPort) EXPECT() *MockGetSensorsByGatewayIdPortMockRecorder {
	return m.recorder
}

// GetSensorsByGatewayId mocks base method.
func (m *MockGetSensorsByGatewayIdPort) GetSensorsByGatewayId(gatewayId uuid.UUID, page, limit int) ([]sensor.Sensor, uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSensorsByGatewayId", gatewayId, page, limit)
	ret0, _ := ret[0].([]sensor.Sensor)
	ret1, _ := ret[1].(uint)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSensorsByGatewayId indicates an expected call of GetSensorsByGatewayId.
func (mr *MockGetSensorsByGatewayIdPortMockRecorder) GetSensorsByGatewayId(gatewayId, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSensorsByGatewayId", reflect.TypeOf((*MockGetSensorsByGatewayIdPort)(nil).GetSensorsByGatewayId), gatewayId, page, limit)
}
