// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/sensor (interfaces: InterruptSensorUseCase,ResumeSensorUseCase)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/sensor/mocks/use_cases_interrupt_resume.go -package=mocks . InterruptSensorUseCase,ResumeSensorUseCase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	sensor "backend/internal/sensor"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockInterruptSensorUseCase is a mock of InterruptSensorUseCase interface.
type MockInterruptSensorUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockInterruptSensorUseCaseMockRecorder
	isgomock struct{}
}

// MockInterruptSensorUseCaseMockRecorder is the mock recorder for MockInterruptSensorUseCase.
type MockInterruptSensorUseCaseMockRecorder struct {
	mock *MockInterruptSensorUseCase
}

// NewMockInterruptSensorUseCase creates a new mock instance.
func NewMockInterruptSensorUseCase(ctrl *gomock.Controller) *MockInterruptSensorUseCase {
	mock := &MockInterruptSensorUseCase{ctrl: ctrl}
	mock.recorder = &MockInterruptSensorUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterruptSensorUseCase) EXPECT() *MockInterruptSensorUseCaseMockRecorder {
	return m.recorder
}

// InterruptSensor mocks base method.
func (m *MockInterruptSensorUseCase) InterruptSensor(cmd sensor.InterruptSensorCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InterruptSensor", cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// InterruptSensor indicates an expected call of InterruptSensor.
func (mr *MockInterruptSensorUseCaseMockRecorder) InterruptSensor(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InterruptSensor", reflect.TypeOf((*MockInterruptSensorUseCase)(nil).InterruptSensor), cmd)
}

// MockResumeSensorUseCase is a mock of ResumeSensorUseCase interface.
type MockResumeSensorUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockResumeSensorUseCaseMockRecorder
	isgomock struct{}
}

// MockResumeSensorUseCaseMockRecorder is the mock recorder for MockResumeSensorUseCase.
type MockResumeSensorUseCaseMockRecorder struct {
	mock *MockResumeSensorUseCase
}

// NewMockResumeSensorUseCase creates a new mock instance.
func NewMockResumeSensorUseCase(ctrl *gomock.Controller) *MockResumeSensorUseCase {
	mock := &MockResumeSensorUseCase{ctrl: ctrl}
	mock.recorder = &MockResumeSensorUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResumeSensorUseCase) EXPECT() *MockResumeSensorUseCaseMockRecorder {
	return m.recorder
}

// ResumeSensor mocks base method.
func (m *MockResumeSensorUseCase) ResumeSensor(cmd sensor.ResumeSensorCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResumeSensor", cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResumeSensor indicates an expected call of ResumeSensor.
func (mr *MockResumeSensorUseCaseMockRecorder) ResumeSensor(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumeSensor", reflect.TypeOf((*MockResumeSensorUseCase)(nil).ResumeSensor), cmd)
}
