// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/sensor (interfaces: CreateSensorUseCase,DeleteSensorUseCase)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/sensor/mocks/use_cases_create_delete.go -package=mocks . CreateSensorUseCase,DeleteSensorUseCase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	sensor "backend/internal/sensor"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCreateSensorUseCase is a mock of CreateSensorUseCase interface.
type MockCreateSensorUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCreateSensorUseCaseMockRecorder
	isgomock struct{}
}

// MockCreateSensorUseCaseMockRecorder is the mock recorder for MockCreateSensorUseCase.
type MockCreateSensorUseCaseMockRecorder struct {
	mock *MockCreateSensorUseCase
}

// NewMockCreateSensorUseCase creates a new mock instance.
func NewMockCreateSensorUseCase(ctrl *gomock.Controller) *MockCreateSensorUseCase {
	mock := &MockCreateSensorUseCase{ctrl: ctrl}
	mock.recorder = &MockCreateSensorUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateSensorUseCase) EXPECT() *MockCreateSensorUseCaseMockRecorder {
	return m.recorder
}

// CreateSensor mocks base method.
func (m *MockCreateSensorUseCase) CreateSensor(cmd sensor.CreateSensorCommand) (sensor.Sensor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSensor", cmd)
	ret0, _ := ret[0].(sensor.Sensor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSensor indicates an expected call of CreateSensor.
func (mr *MockCreateSensorUseCaseMockRecorder) CreateSensor(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSensor", reflect.TypeOf((*MockCreateSensorUseCase)(nil).CreateSensor), cmd)
}

// MockDeleteSensorUseCase is a mock of DeleteSensorUseCase interface.
type MockDeleteSensorUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteSensorUseCaseMockRecorder
	isgomock struct{}
}

// MockDeleteSensorUseCaseMockRecorder is the mock recorder for MockDeleteSensorUseCase.
type MockDeleteSensorUseCaseMockRecorder struct {
	mock *MockDeleteSensorUseCase
}

// NewMockDeleteSensorUseCase creates a new mock instance.
func NewMockDeleteSensorUseCase(ctrl *gomock.Controller) *MockDeleteSensorUseCase {
	mock := &MockDeleteSensorUseCase{ctrl: ctrl}
	mock.recorder = &MockDeleteSensorUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteSensorUseCase) EXPECT() *MockDeleteSensorUseCaseMockRecorder {
	return m.recorder
}

// DeleteSensor mocks base method.
func (m *MockDeleteSensorUseCase) DeleteSensor(cmd sensor.DeleteSensorCommand) (sensor.Sensor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSensor", cmd)
	ret0, _ := ret[0].(sensor.Sensor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteSensor indicates an expected call of DeleteSensor.
func (mr *MockDeleteSensorUseCaseMockRecorder) DeleteSensor(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSensor", reflect.TypeOf((*MockDeleteSensorUseCase)(nil).DeleteSensor), cmd)
}
