// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/sensor (interfaces: GetSensorUseCase,GetSensorsByGatewayUseCase,GetSensorsByTenantUseCase)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/sensor/mocks/use_cases_getters.go -package=mocks . GetSensorUseCase,GetSensorsByGatewayUseCase,GetSensorsByTenantUseCase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	sensor "backend/internal/sensor"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGetSensorUseCase is a mock of GetSensorUseCase interface.
type MockGetSensorUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetSensorUseCaseMockRecorder
	isgomock struct{}
}

// MockGetSensorUseCaseMockRecorder is the mock recorder for MockGetSensorUseCase.
type MockGetSensorUseCaseMockRecorder struct {
	mock *MockGetSensorUseCase
}

// NewMockGetSensorUseCase creates a new mock instance.
func NewMockGetSensorUseCase(ctrl *gomock.Controller) *MockGetSensorUseCase {
	mock := &MockGetSensorUseCase{ctrl: ctrl}
	mock.recorder = &MockGetSensorUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetSensorUseCase) EXPECT() *MockGetSensorUseCaseMockRecorder {
	return m.recorder
}

// GetSensorById mocks base method.
func (m *MockGetSensorUseCase) GetSensorById(cmd sensor.GetSensorCommand) (sensor.Sensor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSensorById", cmd)
	ret0, _ := ret[0].(sensor.Sensor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSensorById indicates an expected call of GetSensorById.
func (mr *MockGetSensorUseCaseMockRecorder) GetSensorById(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSensorById", reflect.TypeOf((*MockGetSensorUseCase)(nil).GetSensorById), cmd)
}

// MockGetSensorsByGatewayUseCase is a mock of GetSensorsByGatewayUseCase interface.
type MockGetSensorsByGatewayUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetSensorsByGatewayUseCaseMockRecorder
	isgomock struct{}
}

// MockGetSensorsByGatewayUseCaseMockRecorder is the mock recorder for MockGetSensorsByGatewayUseCase.
type MockGetSensorsByGatewayUseCaseMockRecorder struct {
	mock *MockGetSensorsByGatewayUseCase
}

// NewMockGetSensorsByGatewayUseCase creates a new mock instance.
func NewMockGetSensorsByGatewayUseCase(ctrl *gomock.Controller) *MockGetSensorsByGatewayUseCase {
	mock := &MockGetSensorsByGatewayUseCase{ctrl: ctrl}
	mock.recorder = &MockGetSensorsByGatewayUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetSensorsByGatewayUseCase) EXPECT() *MockGetSensorsByGatewayUseCaseMockRecorder {
	return m.recorder
}

// GetSensorsByGateway mocks base method.
func (m *MockGetSensorsByGatewayUseCase) GetSensorsByGateway(cmd sensor.GetSensorsByGatewayCommand) ([]sensor.Sensor, uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSensorsByGateway", cmd)
	ret0, _ := ret[0].([]sensor.Sensor)
	ret1, _ := ret[1].(uint)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSensorsByGateway indicates an expected call of GetSensorsByGateway.
func (mr *MockGetSensorsByGatewayUseCaseMockRecorder) GetSensorsByGateway(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSensorsByGateway", reflect.TypeOf((*MockGetSensorsByGatewayUseCase)(nil).GetSensorsByGateway), cmd)
}

// MockGetSensorsByTenantUseCase is a mock of GetSensorsByTenantUseCase interface.
type MockGetSensorsByTenantUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetSensorsByTenantUseCaseMockRecorder
	isgomock struct{}
}

// MockGetSensorsByTenantUseCaseMockRecorder is the mock recorder for MockGetSensorsByTenantUseCase.
type MockGetSensorsByTenantUseCaseMockRecorder struct {
	mock *MockGetSensorsByTenantUseCase
}

// NewMockGetSensorsByTenantUseCase creates a new mock instance.
func NewMockGetSensorsByTenantUseCase(ctrl *gomock.Controller) *MockGetSensorsByTenantUseCase {
	mock := &MockGetSensorsByTenantUseCase{ctrl: ctrl}
	mock.recorder = &MockGetSensorsByTenantUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetSensorsByTenantUseCase) EXPECT() *MockGetSensorsByTenantUseCaseMockRecorder {
	return m.recorder
}

// GetSensorsByTenant mocks base method.
func (m *MockGetSensorsByTenantUseCase) GetSensorsByTenant(cmd sensor.GetSensorsByTenantCommand) ([]sensor.Sensor, uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSensorsByTenant", cmd)
	ret0, _ := ret[0].([]sensor.Sensor)
	ret1, _ := ret[1].(uint)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSensorsByTenant indicates an expected call of GetSensorsByTenant.
func (mr *MockGetSensorsByTenantUseCaseMockRecorder) GetSensorsByTenant(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSensorsByTenant", reflect.TypeOf((*MockGetSensorsByTenantUseCase)(nil).GetSensorsByTenant), cmd)
}
