// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/gateway (interfaces: CreateGatewayUseCase,DeleteGatewayUseCase,GetGatewayUseCase,GetAllGatewaysUseCase,GetGatewaysByTenantUseCase,CommissionGatewayUseCase,DecommissionGatewayUseCase,InterruptGatewayUseCase,ResumeGatewayUseCase,ResetGatewayUseCase,RebootGatewayUseCase)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/gateway/mocks/gateway_usecases.go -package=mocks . CreateGatewayUseCase,DeleteGatewayUseCase,GetGatewayUseCase,GetAllGatewaysUseCase,GetGatewaysByTenantUseCase,CommissionGatewayUseCase,DecommissionGatewayUseCase,InterruptGatewayUseCase,ResumeGatewayUseCase,ResetGatewayUseCase,RebootGatewayUseCase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	gateway "backend/internal/gateway"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCreateGatewayUseCase is a mock of CreateGatewayUseCase interface.
type MockCreateGatewayUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCreateGatewayUseCaseMockRecorder
	isgomock struct{}
}

// MockCreateGatewayUseCaseMockRecorder is the mock recorder for MockCreateGatewayUseCase.
type MockCreateGatewayUseCaseMockRecorder struct {
	mock *MockCreateGatewayUseCase
}

// NewMockCreateGatewayUseCase creates a new mock instance.
func NewMockCreateGatewayUseCase(ctrl *gomock.Controller) *MockCreateGatewayUseCase {
	mock := &MockCreateGatewayUseCase{ctrl: ctrl}
	mock.recorder = &MockCreateGatewayUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateGatewayUseCase) EXPECT() *MockCreateGatewayUseCaseMockRecorder {
	return m.recorder
}

// CreateGateway mocks base method.
func (m *MockCreateGatewayUseCase) CreateGateway(command gateway.CreateGatewayCommand) (gateway.Gateway, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGateway", command)
	ret0, _ := ret[0].(gateway.Gateway)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGateway indicates an expected call of CreateGateway.
func (mr *MockCreateGatewayUseCaseMockRecorder) CreateGateway(command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGateway", reflect.TypeOf((*MockCreateGatewayUseCase)(nil).CreateGateway), command)
}

// MockDeleteGatewayUseCase is a mock of DeleteGatewayUseCase interface.
type MockDeleteGatewayUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteGatewayUseCaseMockRecorder
	isgomock struct{}
}

// MockDeleteGatewayUseCaseMockRecorder is the mock recorder for MockDeleteGatewayUseCase.
type MockDeleteGatewayUseCaseMockRecorder struct {
	mock *MockDeleteGatewayUseCase
}

// NewMockDeleteGatewayUseCase creates a new mock instance.
func NewMockDeleteGatewayUseCase(ctrl *gomock.Controller) *MockDeleteGatewayUseCase {
	mock := &MockDeleteGatewayUseCase{ctrl: ctrl}
	mock.recorder = &MockDeleteGatewayUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteGatewayUseCase) EXPECT() *MockDeleteGatewayUseCaseMockRecorder {
	return m.recorder
}

// DeleteGateway mocks base method.
func (m *MockDeleteGatewayUseCase) DeleteGateway(cmd gateway.DeleteGatewayCommand) (gateway.Gateway, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGateway", cmd)
	ret0, _ := ret[0].(gateway.Gateway)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteGateway indicates an expected call of DeleteGateway.
func (mr *MockDeleteGatewayUseCaseMockRecorder) DeleteGateway(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGateway", reflect.TypeOf((*MockDeleteGatewayUseCase)(nil).DeleteGateway), cmd)
}

// MockGetGatewayUseCase is a mock of GetGatewayUseCase interface.
type MockGetGatewayUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetGatewayUseCaseMockRecorder
	isgomock struct{}
}

// MockGetGatewayUseCaseMockRecorder is the mock recorder for MockGetGatewayUseCase.
type MockGetGatewayUseCaseMockRecorder struct {
	mock *MockGetGatewayUseCase
}

// NewMockGetGatewayUseCase creates a new mock instance.
func NewMockGetGatewayUseCase(ctrl *gomock.Controller) *MockGetGatewayUseCase {
	mock := &MockGetGatewayUseCase{ctrl: ctrl}
	mock.recorder = &MockGetGatewayUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetGatewayUseCase) EXPECT() *MockGetGatewayUseCaseMockRecorder {
	return m.recorder
}

// GetGateway mocks base method.
func (m *MockGetGatewayUseCase) GetGateway(cmd gateway.GetGatewayByIdCommand) (gateway.Gateway, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGateway", cmd)
	ret0, _ := ret[0].(gateway.Gateway)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGateway indicates an expected call of GetGateway.
func (mr *MockGetGatewayUseCaseMockRecorder) GetGateway(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGateway", reflect.TypeOf((*MockGetGatewayUseCase)(nil).GetGateway), cmd)
}

// MockGetAllGatewaysUseCase is a mock of GetAllGatewaysUseCase interface.
type MockGetAllGatewaysUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetAllGatewaysUseCaseMockRecorder
	isgomock struct{}
}

// MockGetAllGatewaysUseCaseMockRecorder is the mock recorder for MockGetAllGatewaysUseCase.
type MockGetAllGatewaysUseCaseMockRecorder struct {
	mock *MockGetAllGatewaysUseCase
}

// NewMockGetAllGatewaysUseCase creates a new mock instance.
func NewMockGetAllGatewaysUseCase(ctrl *gomock.Controller) *MockGetAllGatewaysUseCase {
	mock := &MockGetAllGatewaysUseCase{ctrl: ctrl}
	mock.recorder = &MockGetAllGatewaysUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetAllGatewaysUseCase) EXPECT() *MockGetAllGatewaysUseCaseMockRecorder {
	return m.recorder
}

// GetAllGateways mocks base method.
func (m *MockGetAllGatewaysUseCase) GetAllGateways(command gateway.GetAllGatewaysCommand) ([]gateway.Gateway, uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllGateways", command)
	ret0, _ := ret[0].([]gateway.Gateway)
	ret1, _ := ret[1].(uint)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllGateways indicates an expected call of GetAllGateways.
func (mr *MockGetAllGatewaysUseCaseMockRecorder) GetAllGateways(command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllGateways", reflect.TypeOf((*MockGetAllGatewaysUseCase)(nil).GetAllGateways), command)
}

// MockGetGatewaysByTenantUseCase is a mock of GetGatewaysByTenantUseCase interface.
type MockGetGatewaysByTenantUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetGatewaysByTenantUseCaseMockRecorder
	isgomock struct{}
}

// MockGetGatewaysByTenantUseCaseMockRecorder is the mock recorder for MockGetGatewaysByTenantUseCase.
type MockGetGatewaysByTenantUseCaseMockRecorder struct {
	mock *MockGetGatewaysByTenantUseCase
}

// NewMockGetGatewaysByTenantUseCase creates a new mock instance.
func NewMockGetGatewaysByTenantUseCase(ctrl *gomock.Controller) *MockGetGatewaysByTenantUseCase {
	mock := &MockGetGatewaysByTenantUseCase{ctrl: ctrl}
	mock.recorder = &MockGetGatewaysByTenantUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetGatewaysByTenantUseCase) EXPECT() *MockGetGatewaysByTenantUseCaseMockRecorder {
	return m.recorder
}

// GetGatewaysByTenant mocks base method.
func (m *MockGetGatewaysByTenantUseCase) GetGatewaysByTenant(command gateway.GetGatewaysByTenantCommand) ([]gateway.Gateway, uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGatewaysByTenant", command)
	ret0, _ := ret[0].([]gateway.Gateway)
	ret1, _ := ret[1].(uint)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetGatewaysByTenant indicates an expected call of GetGatewaysByTenant.
func (mr *MockGetGatewaysByTenantUseCaseMockRecorder) GetGatewaysByTenant(command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGatewaysByTenant", reflect.TypeOf((*MockGetGatewaysByTenantUseCase)(nil).GetGatewaysByTenant), command)
}

// MockCommissionGatewayUseCase is a mock of CommissionGatewayUseCase interface.
type MockCommissionGatewayUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCommissionGatewayUseCaseMockRecorder
	isgomock struct{}
}

// MockCommissionGatewayUseCaseMockRecorder is the mock recorder for MockCommissionGatewayUseCase.
type MockCommissionGatewayUseCaseMockRecorder struct {
	mock *MockCommissionGatewayUseCase
}

// NewMockCommissionGatewayUseCase creates a new mock instance.
func NewMockCommissionGatewayUseCase(ctrl *gomock.Controller) *MockCommissionGatewayUseCase {
	mock := &MockCommissionGatewayUseCase{ctrl: ctrl}
	mock.recorder = &MockCommissionGatewayUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommissionGatewayUseCase) EXPECT() *MockCommissionGatewayUseCaseMockRecorder {
	return m.recorder
}

// CommissionGateway mocks base method.
func (m *MockCommissionGatewayUseCase) CommissionGateway(cmd gateway.CommissionGatewayCommand) (gateway.Gateway, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommissionGateway", cmd)
	ret0, _ := ret[0].(gateway.Gateway)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommissionGateway indicates an expected call of CommissionGateway.
func (mr *MockCommissionGatewayUseCaseMockRecorder) CommissionGateway(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommissionGateway", reflect.TypeOf((*MockCommissionGatewayUseCase)(nil).CommissionGateway), cmd)
}

// MockDecommissionGatewayUseCase is a mock of DecommissionGatewayUseCase interface.
type MockDecommissionGatewayUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockDecommissionGatewayUseCaseMockRecorder
	isgomock struct{}
}

// MockDecommissionGatewayUseCaseMockRecorder is the mock recorder for MockDecommissionGatewayUseCase.
type MockDecommissionGatewayUseCaseMockRecorder struct {
	mock *MockDecommissionGatewayUseCase
}

// NewMockDecommissionGatewayUseCase creates a new mock instance.
func NewMockDecommissionGatewayUseCase(ctrl *gomock.Controller) *MockDecommissionGatewayUseCase {
	mock := &MockDecommissionGatewayUseCase{ctrl: ctrl}
	mock.recorder = &MockDecommissionGatewayUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDecommissionGatewayUseCase) EXPECT() *MockDecommissionGatewayUseCaseMockRecorder {
	return m.recorder
}

// DecommissionGateway mocks base method.
func (m *MockDecommissionGatewayUseCase) DecommissionGateway(cmd gateway.DecommissionGatewayCommand) (gateway.Gateway, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecommissionGateway", cmd)
	ret0, _ := ret[0].(gateway.Gateway)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecommissionGateway indicates an expected call of DecommissionGateway.
func (mr *MockDecommissionGatewayUseCaseMockRecorder) DecommissionGateway(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecommissionGateway", reflect.TypeOf((*MockDecommissionGatewayUseCase)(nil).DecommissionGateway), cmd)
}

// MockInterruptGatewayUseCase is a mock of InterruptGatewayUseCase interface.
type MockInterruptGatewayUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockInterruptGatewayUseCaseMockRecorder
	isgomock struct{}
}

// MockInterruptGatewayUseCaseMockRecorder is the mock recorder for MockInterruptGatewayUseCase.
type MockInterruptGatewayUseCaseMockRecorder struct {
	mock *MockInterruptGatewayUseCase
}

// NewMockInterruptGatewayUseCase creates a new mock instance.
func NewMockInterruptGatewayUseCase(ctrl *gomock.Controller) *MockInterruptGatewayUseCase {
	mock := &MockInterruptGatewayUseCase{ctrl: ctrl}
	mock.recorder = &MockInterruptGatewayUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterruptGatewayUseCase) EXPECT() *MockInterruptGatewayUseCaseMockRecorder {
	return m.recorder
}

// InterruptGateway mocks base method.
func (m *MockInterruptGatewayUseCase) InterruptGateway(cmd gateway.InterruptGatewayCommand) (gateway.Gateway, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InterruptGateway", cmd)
	ret0, _ := ret[0].(gateway.Gateway)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InterruptGateway indicates an expected call of InterruptGateway.
func (mr *MockInterruptGatewayUseCaseMockRecorder) InterruptGateway(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InterruptGateway", reflect.TypeOf((*MockInterruptGatewayUseCase)(nil).InterruptGateway), cmd)
}

// MockResumeGatewayUseCase is a mock of ResumeGatewayUseCase interface.
type MockResumeGatewayUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockResumeGatewayUseCaseMockRecorder
	isgomock struct{}
}

// MockResumeGatewayUseCaseMockRecorder is the mock recorder for MockResumeGatewayUseCase.
type MockResumeGatewayUseCaseMockRecorder struct {
	mock *MockResumeGatewayUseCase
}

// NewMockResumeGatewayUseCase creates a new mock instance.
func NewMockResumeGatewayUseCase(ctrl *gomock.Controller) *MockResumeGatewayUseCase {
	mock := &MockResumeGatewayUseCase{ctrl: ctrl}
	mock.recorder = &MockResumeGatewayUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResumeGatewayUseCase) EXPECT() *MockResumeGatewayUseCaseMockRecorder {
	return m.recorder
}

// ResumeGateway mocks base method.
func (m *MockResumeGatewayUseCase) ResumeGateway(cmd gateway.ResumeGatewayCommand) (gateway.Gateway, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResumeGateway", cmd)
	ret0, _ := ret[0].(gateway.Gateway)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResumeGateway indicates an expected call of ResumeGateway.
func (mr *MockResumeGatewayUseCaseMockRecorder) ResumeGateway(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumeGateway", reflect.TypeOf((*MockResumeGatewayUseCase)(nil).ResumeGateway), cmd)
}

// MockResetGatewayUseCase is a mock of ResetGatewayUseCase interface.
type MockResetGatewayUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockResetGatewayUseCaseMockRecorder
	isgomock struct{}
}

// MockResetGatewayUseCaseMockRecorder is the mock recorder for MockResetGatewayUseCase.
type MockResetGatewayUseCaseMockRecorder struct {
	mock *MockResetGatewayUseCase
}

// NewMockResetGatewayUseCase creates a new mock instance.
func NewMockResetGatewayUseCase(ctrl *gomock.Controller) *MockResetGatewayUseCase {
	mock := &MockResetGatewayUseCase{ctrl: ctrl}
	mock.recorder = &MockResetGatewayUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResetGatewayUseCase) EXPECT() *MockResetGatewayUseCaseMockRecorder {
	return m.recorder
}

// ResetGateway mocks base method.
func (m *MockResetGatewayUseCase) ResetGateway(cmd gateway.ResetGatewayCommand) (gateway.Gateway, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetGateway", cmd)
	ret0, _ := ret[0].(gateway.Gateway)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResetGateway indicates an expected call of ResetGateway.
func (mr *MockResetGatewayUseCaseMockRecorder) ResetGateway(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetGateway", reflect.TypeOf((*MockResetGatewayUseCase)(nil).ResetGateway), cmd)
}

// MockRebootGatewayUseCase is a mock of RebootGatewayUseCase interface.
type MockRebootGatewayUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockRebootGatewayUseCaseMockRecorder
	isgomock struct{}
}

// MockRebootGatewayUseCaseMockRecorder is the mock recorder for MockRebootGatewayUseCase.
type MockRebootGatewayUseCaseMockRecorder struct {
	mock *MockRebootGatewayUseCase
}

// NewMockRebootGatewayUseCase creates a new mock instance.
func NewMockRebootGatewayUseCase(ctrl *gomock.Controller) *MockRebootGatewayUseCase {
	mock := &MockRebootGatewayUseCase{ctrl: ctrl}
	mock.recorder = &MockRebootGatewayUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRebootGatewayUseCase) EXPECT() *MockRebootGatewayUseCaseMockRecorder {
	return m.recorder
}

// RebootGateway mocks base method.
func (m *MockRebootGatewayUseCase) RebootGateway(cmd gateway.RebootGatewayCommand) (gateway.Gateway, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RebootGateway", cmd)
	ret0, _ := ret[0].(gateway.Gateway)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RebootGateway indicates an expected call of RebootGateway.
func (mr *MockRebootGatewayUseCaseMockRecorder) RebootGateway(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RebootGateway", reflect.TypeOf((*MockRebootGatewayUseCase)(nil).RebootGateway), cmd)
}
