// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/gateway (interfaces: GatewayCommandPort)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/gateway/mocks/gateway_command_port.go -package=mocks . GatewayCommandPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockGatewayCommandPort is a mock of GatewayCommandPort interface.
type MockGatewayCommandPort struct {
	ctrl     *gomock.Controller
	recorder *MockGatewayCommandPortMockRecorder
	isgomock struct{}
}

// MockGatewayCommandPortMockRecorder is the mock recorder for MockGatewayCommandPort.
type MockGatewayCommandPortMockRecorder struct {
	mock *MockGatewayCommandPort
}

// NewMockGatewayCommandPort creates a new mock instance.
func NewMockGatewayCommandPort(ctrl *gomock.Controller) *MockGatewayCommandPort {
	mock := &MockGatewayCommandPort{ctrl: ctrl}
	mock.recorder = &MockGatewayCommandPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGatewayCommandPort) EXPECT() *MockGatewayCommandPortMockRecorder {
	return m.recorder
}

// SendCommission mocks base method.
func (m *MockGatewayCommandPort) SendCommission(gatewayId, tenantId uuid.UUID, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendCommission", gatewayId, tenantId, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendCommission indicates an expected call of SendCommission.
func (mr *MockGatewayCommandPortMockRecorder) SendCommission(gatewayId, tenantId, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendCommission", reflect.TypeOf((*MockGatewayCommandPort)(nil).SendCommission), gatewayId, tenantId, token)
}

// SendCreateGateway mocks base method.
func (m *MockGatewayCommandPort) SendCreateGateway(gatewayId uuid.UUID, interval int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendCreateGateway", gatewayId, interval)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendCreateGateway indicates an expected call of SendCreateGateway.
func (mr *MockGatewayCommandPortMockRecorder) SendCreateGateway(gatewayId, interval any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendCreateGateway", reflect.TypeOf((*MockGatewayCommandPort)(nil).SendCreateGateway), gatewayId, interval)
}

// SendDecommission mocks base method.
func (m *MockGatewayCommandPort) SendDecommission(gatewayId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendDecommission", gatewayId)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendDecommission indicates an expected call of SendDecommission.
func (mr *MockGatewayCommandPortMockRecorder) SendDecommission(gatewayId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendDecommission", reflect.TypeOf((*MockGatewayCommandPort)(nil).SendDecommission), gatewayId)
}

// SendDeleteGateway mocks base method.
func (m *MockGatewayCommandPort) SendDeleteGateway(gatewayId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendDeleteGateway", gatewayId)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendDeleteGateway indicates an expected call of SendDeleteGateway.
func (mr *MockGatewayCommandPortMockRecorder) SendDeleteGateway(gatewayId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendDeleteGateway", reflect.TypeOf((*MockGatewayCommandPort)(nil).SendDeleteGateway), gatewayId)
}

// SendInterrupt mocks base method.
func (m *MockGatewayCommandPort) SendInterrupt(gatewayId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendInterrupt", gatewayId)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendInterrupt indicates an expected call of SendInterrupt.
func (mr *MockGatewayCommandPortMockRecorder) SendInterrupt(gatewayId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendInterrupt", reflect.TypeOf((*MockGatewayCommandPort)(nil).SendInterrupt), gatewayId)
}

// SendReboot mocks base method.
func (m *MockGatewayCommandPort) SendReboot(gatewayId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendReboot", gatewayId)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendReboot indicates an expected call of SendReboot.
func (mr *MockGatewayCommandPortMockRecorder) SendReboot(gatewayId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendReboot", reflect.TypeOf((*MockGatewayCommandPort)(nil).SendReboot), gatewayId)
}

// SendReset mocks base method.
func (m *MockGatewayCommandPort) SendReset(gatewayId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendReset", gatewayId)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendReset indicates an expected call of SendReset.
func (mr *MockGatewayCommandPortMockRecorder) SendReset(gatewayId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendReset", reflect.TypeOf((*MockGatewayCommandPort)(nil).SendReset), gatewayId)
}

// SendResume mocks base method.
func (m *MockGatewayCommandPort) SendResume(gatewayId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendResume", gatewayId)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendResume indicates an expected call of SendResume.
func (mr *MockGatewayCommandPortMockRecorder) SendResume(gatewayId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendResume", reflect.TypeOf((*MockGatewayCommandPort)(nil).SendResume), gatewayId)
}
