// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/gateway (interfaces: SaveGatewayPort)

package mocks

import (
	gateway "backend/internal/gateway"
	"reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSaveGatewayPort is a mock of SaveGatewayPort interface.
type MockSaveGatewayPort struct {
	ctrl     *gomock.Controller
	recorder *MockSaveGatewayPortMockRecorder
	isgomock struct{}
}

// MockSaveGatewayPortMockRecorder is the mock recorder for MockSaveGatewayPort.
type MockSaveGatewayPortMockRecorder struct {
	mock *MockSaveGatewayPort
}

// NewMockSaveGatewayPort creates a new mock instance.
func NewMockSaveGatewayPort(ctrl *gomock.Controller) *MockSaveGatewayPort {
	mock := &MockSaveGatewayPort{ctrl: ctrl}
	mock.recorder = &MockSaveGatewayPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSaveGatewayPort) EXPECT() *MockSaveGatewayPortMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockSaveGatewayPort) Save(g gateway.Gateway) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", g)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockSaveGatewayPortMockRecorder) Save(g any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSaveGatewayPort)(nil).Save), g)
}
