// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/gateway (interfaces: GatewayRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/gateway/mocks/repository.go -package=mocks . GatewayRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	gateway "backend/internal/gateway"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGatewayRepository is a mock of GatewayRepository interface.
type MockGatewayRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGatewayRepositoryMockRecorder
	isgomock struct{}
}

// MockGatewayRepositoryMockRecorder is the mock recorder for MockGatewayRepository.
type MockGatewayRepositoryMockRecorder struct {
	mock *MockGatewayRepository
}

// NewMockGatewayRepository creates a new mock instance.
func NewMockGatewayRepository(ctrl *gomock.Controller) *MockGatewayRepository {
	mock := &MockGatewayRepository{ctrl: ctrl}
	mock.recorder = &MockGatewayRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGatewayRepository) EXPECT() *MockGatewayRepositoryMockRecorder {
	return m.recorder
}

// CreateGateway mocks base method.
func (m *MockGatewayRepository) CreateGateway(entity *gateway.GatewayEntity) (gateway.Gateway, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGateway", entity)
	ret0, _ := ret[0].(gateway.Gateway)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGateway indicates an expected call of CreateGateway.
func (mr *MockGatewayRepositoryMockRecorder) CreateGateway(entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGateway", reflect.TypeOf((*MockGatewayRepository)(nil).CreateGateway), entity)
}

// DeleteGateway mocks base method.
func (m *MockGatewayRepository) DeleteGateway(entity *gateway.GatewayEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGateway", entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGateway indicates an expected call of DeleteGateway.
func (mr *MockGatewayRepositoryMockRecorder) DeleteGateway(entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGateway", reflect.TypeOf((*MockGatewayRepository)(nil).DeleteGateway), entity)
}

// GetAllGateways mocks base method.
func (m *MockGatewayRepository) GetAllGateways(offset, limit int) ([]gateway.GatewayEntity, uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllGateways", offset, limit)
	ret0, _ := ret[0].([]gateway.GatewayEntity)
	ret1, _ := ret[1].(uint)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllGateways indicates an expected call of GetAllGateways.
func (mr *MockGatewayRepositoryMockRecorder) GetAllGateways(offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllGateways", reflect.TypeOf((*MockGatewayRepository)(nil).GetAllGateways), offset, limit)
}

// GetGatewayById mocks base method.
func (m *MockGatewayRepository) GetGatewayById(gatewayId string) (gateway.GatewayEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGatewayById", gatewayId)
	ret0, _ := ret[0].(gateway.GatewayEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGatewayById indicates an expected call of GetGatewayById.
func (mr *MockGatewayRepositoryMockRecorder) GetGatewayById(gatewayId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGatewayById", reflect.TypeOf((*MockGatewayRepository)(nil).GetGatewayById), gatewayId)
}

// GetGatewayByTenantID mocks base method.
func (m *MockGatewayRepository) GetGatewayByTenantID(tenantId, gatewayId string) (gateway.GatewayEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGatewayByTenantID", tenantId, gatewayId)
	ret0, _ := ret[0].(gateway.GatewayEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGatewayByTenantID indicates an expected call of GetGatewayByTenantID.
func (mr *MockGatewayRepositoryMockRecorder) GetGatewayByTenantID(tenantId, gatewayId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGatewayByTenantID", reflect.TypeOf((*MockGatewayRepository)(nil).GetGatewayByTenantID), tenantId, gatewayId)
}

// GetGatewaysByTenantId mocks base method.
func (m *MockGatewayRepository) GetGatewaysByTenantId(tenantId string, offset, limit int) ([]gateway.GatewayEntity, uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGatewaysByTenantId", tenantId, offset, limit)
	ret0, _ := ret[0].([]gateway.GatewayEntity)
	ret1, _ := ret[1].(uint)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetGatewaysByTenantId indicates an expected call of GetGatewaysByTenantId.
func (mr *MockGatewayRepositoryMockRecorder) GetGatewaysByTenantId(tenantId, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGatewaysByTenantId", reflect.TypeOf((*MockGatewayRepository)(nil).GetGatewaysByTenantId), tenantId, offset, limit)
}

// SaveGateway mocks base method.
func (m *MockGatewayRepository) SaveGateway(entity *gateway.GatewayEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveGateway", entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveGateway indicates an expected call of SaveGateway.
func (mr *MockGatewayRepositoryMockRecorder) SaveGateway(entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveGateway", reflect.TypeOf((*MockGatewayRepository)(nil).SaveGateway), entity)
}
