// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/gateway (interfaces: SaveGatewayPort,RemoveGatewayPort,GetGatewayPort)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/gateway/mocks/save_remove_get_port.go -package=mocks . SaveGatewayPort,RemoveGatewayPort,GetGatewayPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	gateway "backend/internal/gateway"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockSaveGatewayPort is a mock of SaveGatewayPort interface.
type MockSaveGatewayPort struct {
	ctrl     *gomock.Controller
	recorder *MockSaveGatewayPortMockRecorder
	isgomock struct{}
}

// MockSaveGatewayPortMockRecorder is the mock recorder for MockSaveGatewayPort.
type MockSaveGatewayPortMockRecorder struct {
	mock *MockSaveGatewayPort
}

// NewMockSaveGatewayPort creates a new mock instance.
func NewMockSaveGatewayPort(ctrl *gomock.Controller) *MockSaveGatewayPort {
	mock := &MockSaveGatewayPort{ctrl: ctrl}
	mock.recorder = &MockSaveGatewayPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSaveGatewayPort) EXPECT() *MockSaveGatewayPortMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockSaveGatewayPort) Save(g gateway.Gateway) (gateway.Gateway, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", g)
	ret0, _ := ret[0].(gateway.Gateway)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockSaveGatewayPortMockRecorder) Save(g any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSaveGatewayPort)(nil).Save), g)
}

// MockRemoveGatewayPort is a mock of RemoveGatewayPort interface.
type MockRemoveGatewayPort struct {
	ctrl     *gomock.Controller
	recorder *MockRemoveGatewayPortMockRecorder
	isgomock struct{}
}

// MockRemoveGatewayPortMockRecorder is the mock recorder for MockRemoveGatewayPort.
type MockRemoveGatewayPortMockRecorder struct {
	mock *MockRemoveGatewayPort
}

// NewMockRemoveGatewayPort creates a new mock instance.
func NewMockRemoveGatewayPort(ctrl *gomock.Controller) *MockRemoveGatewayPort {
	mock := &MockRemoveGatewayPort{ctrl: ctrl}
	mock.recorder = &MockRemoveGatewayPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRemoveGatewayPort) EXPECT() *MockRemoveGatewayPortMockRecorder {
	return m.recorder
}

// Remove mocks base method.
func (m *MockRemoveGatewayPort) Remove(gatewayId uuid.UUID) (gateway.Gateway, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", gatewayId)
	ret0, _ := ret[0].(gateway.Gateway)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Remove indicates an expected call of Remove.
func (mr *MockRemoveGatewayPortMockRecorder) Remove(gatewayId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockRemoveGatewayPort)(nil).Remove), gatewayId)
}

// MockGetGatewayPort is a mock of GetGatewayPort interface.
type MockGetGatewayPort struct {
	ctrl     *gomock.Controller
	recorder *MockGetGatewayPortMockRecorder
	isgomock struct{}
}

// MockGetGatewayPortMockRecorder is the mock recorder for MockGetGatewayPort.
type MockGetGatewayPortMockRecorder struct {
	mock *MockGetGatewayPort
}

// NewMockGetGatewayPort creates a new mock instance.
func NewMockGetGatewayPort(ctrl *gomock.Controller) *MockGetGatewayPort {
	mock := &MockGetGatewayPort{ctrl: ctrl}
	mock.recorder = &MockGetGatewayPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetGatewayPort) EXPECT() *MockGetGatewayPortMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockGetGatewayPort) GetAll() ([]gateway.Gateway, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]gateway.Gateway)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockGetGatewayPortMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockGetGatewayPort)(nil).GetAll))
}

// GetById mocks base method.
func (m *MockGetGatewayPort) GetById(gatewayId string) (gateway.Gateway, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", gatewayId)
	ret0, _ := ret[0].(gateway.Gateway)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockGetGatewayPortMockRecorder) GetById(gatewayId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockGetGatewayPort)(nil).GetById), gatewayId)
}

// GetByTenantId mocks base method.
func (m *MockGetGatewayPort) GetByTenantId(tenantId string) ([]gateway.Gateway, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTenantId", tenantId)
	ret0, _ := ret[0].([]gateway.Gateway)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTenantId indicates an expected call of GetByTenantId.
func (mr *MockGetGatewayPortMockRecorder) GetByTenantId(tenantId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTenantId", reflect.TypeOf((*MockGetGatewayPort)(nil).GetByTenantId), tenantId)
}
