// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/gateway (interfaces: CreateGatewayPort,SaveGatewayPort,DeleteGatewayPort,GetGatewayPort,GetGatewaysPort)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/gateway/mocks/save_remove_get_port.go -package=mocks . CreateGatewayPort,SaveGatewayPort,DeleteGatewayPort,GetGatewayPort,GetGatewaysPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	gateway "backend/internal/gateway"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCreateGatewayPort is a mock of CreateGatewayPort interface.
type MockCreateGatewayPort struct {
	ctrl     *gomock.Controller
	recorder *MockCreateGatewayPortMockRecorder
	isgomock struct{}
}

// MockCreateGatewayPortMockRecorder is the mock recorder for MockCreateGatewayPort.
type MockCreateGatewayPortMockRecorder struct {
	mock *MockCreateGatewayPort
}

// NewMockCreateGatewayPort creates a new mock instance.
func NewMockCreateGatewayPort(ctrl *gomock.Controller) *MockCreateGatewayPort {
	mock := &MockCreateGatewayPort{ctrl: ctrl}
	mock.recorder = &MockCreateGatewayPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateGatewayPort) EXPECT() *MockCreateGatewayPortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCreateGatewayPort) Create(g gateway.Gateway) (gateway.Gateway, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", g)
	ret0, _ := ret[0].(gateway.Gateway)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCreateGatewayPortMockRecorder) Create(g any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCreateGatewayPort)(nil).Create), g)
}

// MockSaveGatewayPort is a mock of SaveGatewayPort interface.
type MockSaveGatewayPort struct {
	ctrl     *gomock.Controller
	recorder *MockSaveGatewayPortMockRecorder
	isgomock struct{}
}

// MockSaveGatewayPortMockRecorder is the mock recorder for MockSaveGatewayPort.
type MockSaveGatewayPortMockRecorder struct {
	mock *MockSaveGatewayPort
}

// NewMockSaveGatewayPort creates a new mock instance.
func NewMockSaveGatewayPort(ctrl *gomock.Controller) *MockSaveGatewayPort {
	mock := &MockSaveGatewayPort{ctrl: ctrl}
	mock.recorder = &MockSaveGatewayPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSaveGatewayPort) EXPECT() *MockSaveGatewayPortMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockSaveGatewayPort) Save(g gateway.Gateway) (gateway.Gateway, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", g)
	ret0, _ := ret[0].(gateway.Gateway)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockSaveGatewayPortMockRecorder) Save(g any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSaveGatewayPort)(nil).Save), g)
}

// MockDeleteGatewayPort is a mock of DeleteGatewayPort interface.
type MockDeleteGatewayPort struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteGatewayPortMockRecorder
	isgomock struct{}
}

// MockDeleteGatewayPortMockRecorder is the mock recorder for MockDeleteGatewayPort.
type MockDeleteGatewayPortMockRecorder struct {
	mock *MockDeleteGatewayPort
}

// NewMockDeleteGatewayPort creates a new mock instance.
func NewMockDeleteGatewayPort(ctrl *gomock.Controller) *MockDeleteGatewayPort {
	mock := &MockDeleteGatewayPort{ctrl: ctrl}
	mock.recorder = &MockDeleteGatewayPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteGatewayPort) EXPECT() *MockDeleteGatewayPortMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockDeleteGatewayPort) Delete(gatewayId uuid.UUID) (gateway.Gateway, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", gatewayId)
	ret0, _ := ret[0].(gateway.Gateway)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockDeleteGatewayPortMockRecorder) Delete(gatewayId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDeleteGatewayPort)(nil).Delete), gatewayId)
}

// MockGetGatewayPort is a mock of GetGatewayPort interface.
type MockGetGatewayPort struct {
	ctrl     *gomock.Controller
	recorder *MockGetGatewayPortMockRecorder
	isgomock struct{}
}

// MockGetGatewayPortMockRecorder is the mock recorder for MockGetGatewayPort.
type MockGetGatewayPortMockRecorder struct {
	mock *MockGetGatewayPort
}

// NewMockGetGatewayPort creates a new mock instance.
func NewMockGetGatewayPort(ctrl *gomock.Controller) *MockGetGatewayPort {
	mock := &MockGetGatewayPort{ctrl: ctrl}
	mock.recorder = &MockGetGatewayPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetGatewayPort) EXPECT() *MockGetGatewayPortMockRecorder {
	return m.recorder
}

// GetById mocks base method.
func (m *MockGetGatewayPort) GetById(gatewayId uuid.UUID) (gateway.Gateway, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", gatewayId)
	ret0, _ := ret[0].(gateway.Gateway)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockGetGatewayPortMockRecorder) GetById(gatewayId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockGetGatewayPort)(nil).GetById), gatewayId)
}

// GetGatewayByTenantID mocks base method.
func (m *MockGetGatewayPort) GetGatewayByTenantID(tenantId, gatewayId uuid.UUID) (gateway.Gateway, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGatewayByTenantID", tenantId, gatewayId)
	ret0, _ := ret[0].(gateway.Gateway)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGatewayByTenantID indicates an expected call of GetGatewayByTenantID.
func (mr *MockGetGatewayPortMockRecorder) GetGatewayByTenantID(tenantId, gatewayId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGatewayByTenantID", reflect.TypeOf((*MockGetGatewayPort)(nil).GetGatewayByTenantID), tenantId, gatewayId)
}

// MockGetGatewaysPort is a mock of GetGatewaysPort interface.
type MockGetGatewaysPort struct {
	ctrl     *gomock.Controller
	recorder *MockGetGatewaysPortMockRecorder
	isgomock struct{}
}

// MockGetGatewaysPortMockRecorder is the mock recorder for MockGetGatewaysPort.
type MockGetGatewaysPortMockRecorder struct {
	mock *MockGetGatewaysPort
}

// NewMockGetGatewaysPort creates a new mock instance.
func NewMockGetGatewaysPort(ctrl *gomock.Controller) *MockGetGatewaysPort {
	mock := &MockGetGatewaysPort{ctrl: ctrl}
	mock.recorder = &MockGetGatewaysPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetGatewaysPort) EXPECT() *MockGetGatewaysPortMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockGetGatewaysPort) GetAll(page, limit int) ([]gateway.Gateway, uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", page, limit)
	ret0, _ := ret[0].([]gateway.Gateway)
	ret1, _ := ret[1].(uint)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAll indicates an expected call of GetAll.
func (mr *MockGetGatewaysPortMockRecorder) GetAll(page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockGetGatewaysPort)(nil).GetAll), page, limit)
}

// GetByTenantId mocks base method.
func (m *MockGetGatewaysPort) GetByTenantId(tenantId uuid.UUID, page, limit int) ([]gateway.Gateway, uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTenantId", tenantId, page, limit)
	ret0, _ := ret[0].([]gateway.Gateway)
	ret1, _ := ret[1].(uint)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByTenantId indicates an expected call of GetByTenantId.
func (mr *MockGetGatewaysPortMockRecorder) GetByTenantId(tenantId, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTenantId", reflect.TypeOf((*MockGetGatewaysPort)(nil).GetByTenantId), tenantId, page, limit)
}
