// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/auth (interfaces: ConfirmAccountTokenPort,ChangePasswordTokenPort)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/auth/mocks/ports.go -package=mocks . ConfirmAccountTokenPort,ChangePasswordTokenPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	auth "backend/internal/auth"
	user "backend/internal/user"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockConfirmAccountTokenPort is a mock of ConfirmAccountTokenPort interface.
type MockConfirmAccountTokenPort struct {
	ctrl     *gomock.Controller
	recorder *MockConfirmAccountTokenPortMockRecorder
	isgomock struct{}
}

// MockConfirmAccountTokenPortMockRecorder is the mock recorder for MockConfirmAccountTokenPort.
type MockConfirmAccountTokenPortMockRecorder struct {
	mock *MockConfirmAccountTokenPort
}

// NewMockConfirmAccountTokenPort creates a new mock instance.
func NewMockConfirmAccountTokenPort(ctrl *gomock.Controller) *MockConfirmAccountTokenPort {
	mock := &MockConfirmAccountTokenPort{ctrl: ctrl}
	mock.recorder = &MockConfirmAccountTokenPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfirmAccountTokenPort) EXPECT() *MockConfirmAccountTokenPortMockRecorder {
	return m.recorder
}

// DeleteConfirmAccountToken mocks base method.
func (m *MockConfirmAccountTokenPort) DeleteConfirmAccountToken(token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteConfirmAccountToken", token)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteConfirmAccountToken indicates an expected call of DeleteConfirmAccountToken.
func (mr *MockConfirmAccountTokenPortMockRecorder) DeleteConfirmAccountToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteConfirmAccountToken", reflect.TypeOf((*MockConfirmAccountTokenPort)(nil).DeleteConfirmAccountToken), token)
}

// GetConfirmAccountTokenByUserId mocks base method.
func (m *MockConfirmAccountTokenPort) GetConfirmAccountTokenByUserId(tenantId *uuid.UUID, userId uint) (*auth.ConfirmAccountToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfirmAccountTokenByUserId", tenantId, userId)
	ret0, _ := ret[0].(*auth.ConfirmAccountToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfirmAccountTokenByUserId indicates an expected call of GetConfirmAccountTokenByUserId.
func (mr *MockConfirmAccountTokenPortMockRecorder) GetConfirmAccountTokenByUserId(tenantId, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfirmAccountTokenByUserId", reflect.TypeOf((*MockConfirmAccountTokenPort)(nil).GetConfirmAccountTokenByUserId), tenantId, userId)
}

// GetUserByConfirmAccountToken mocks base method.
func (m *MockConfirmAccountTokenPort) GetUserByConfirmAccountToken(token string) (user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByConfirmAccountToken", token)
	ret0, _ := ret[0].(user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByConfirmAccountToken indicates an expected call of GetUserByConfirmAccountToken.
func (mr *MockConfirmAccountTokenPortMockRecorder) GetUserByConfirmAccountToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByConfirmAccountToken", reflect.TypeOf((*MockConfirmAccountTokenPort)(nil).GetUserByConfirmAccountToken), token)
}

// NewConfirmAccountToken mocks base method.
func (m *MockConfirmAccountTokenPort) NewConfirmAccountToken(tenantId *uuid.UUID, userId uint) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewConfirmAccountToken", tenantId, userId)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewConfirmAccountToken indicates an expected call of NewConfirmAccountToken.
func (mr *MockConfirmAccountTokenPortMockRecorder) NewConfirmAccountToken(tenantId, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewConfirmAccountToken", reflect.TypeOf((*MockConfirmAccountTokenPort)(nil).NewConfirmAccountToken), tenantId, userId)
}

// MockChangePasswordTokenPort is a mock of ChangePasswordTokenPort interface.
type MockChangePasswordTokenPort struct {
	ctrl     *gomock.Controller
	recorder *MockChangePasswordTokenPortMockRecorder
	isgomock struct{}
}

// MockChangePasswordTokenPortMockRecorder is the mock recorder for MockChangePasswordTokenPort.
type MockChangePasswordTokenPortMockRecorder struct {
	mock *MockChangePasswordTokenPort
}

// NewMockChangePasswordTokenPort creates a new mock instance.
func NewMockChangePasswordTokenPort(ctrl *gomock.Controller) *MockChangePasswordTokenPort {
	mock := &MockChangePasswordTokenPort{ctrl: ctrl}
	mock.recorder = &MockChangePasswordTokenPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChangePasswordTokenPort) EXPECT() *MockChangePasswordTokenPortMockRecorder {
	return m.recorder
}

// DeleteChangePasswordToken mocks base method.
func (m *MockChangePasswordTokenPort) DeleteChangePasswordToken(tokenId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChangePasswordToken", tokenId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChangePasswordToken indicates an expected call of DeleteChangePasswordToken.
func (mr *MockChangePasswordTokenPortMockRecorder) DeleteChangePasswordToken(tokenId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChangePasswordToken", reflect.TypeOf((*MockChangePasswordTokenPort)(nil).DeleteChangePasswordToken), tokenId)
}

// GetChangePasswordTokenByUserId mocks base method.
func (m *MockChangePasswordTokenPort) GetChangePasswordTokenByUserId(userId uint) (*auth.ForgotPasswordToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChangePasswordTokenByUserId", userId)
	ret0, _ := ret[0].(*auth.ForgotPasswordToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChangePasswordTokenByUserId indicates an expected call of GetChangePasswordTokenByUserId.
func (mr *MockChangePasswordTokenPortMockRecorder) GetChangePasswordTokenByUserId(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChangePasswordTokenByUserId", reflect.TypeOf((*MockChangePasswordTokenPort)(nil).GetChangePasswordTokenByUserId), userId)
}

// SaveChangePasswordToken mocks base method.
func (m *MockChangePasswordTokenPort) SaveChangePasswordToken(token auth.ForgotPasswordToken) (*auth.ForgotPasswordToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveChangePasswordToken", token)
	ret0, _ := ret[0].(*auth.ForgotPasswordToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveChangePasswordToken indicates an expected call of SaveChangePasswordToken.
func (mr *MockChangePasswordTokenPortMockRecorder) SaveChangePasswordToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveChangePasswordToken", reflect.TypeOf((*MockChangePasswordTokenPort)(nil).SaveChangePasswordToken), token)
}
