// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/auth (interfaces: ConfirmAccountTokenPort)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/auth/mocks/ports.go -package=mocks . ConfirmAccountTokenPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	auth "backend/internal/auth"
	user "backend/internal/user"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockConfirmAccountTokenPort is a mock of ConfirmAccountTokenPort interface.
type MockConfirmAccountTokenPort struct {
	ctrl     *gomock.Controller
	recorder *MockConfirmAccountTokenPortMockRecorder
	isgomock struct{}
}

// MockConfirmAccountTokenPortMockRecorder is the mock recorder for MockConfirmAccountTokenPort.
type MockConfirmAccountTokenPortMockRecorder struct {
	mock *MockConfirmAccountTokenPort
}

// NewMockConfirmAccountTokenPort creates a new mock instance.
func NewMockConfirmAccountTokenPort(ctrl *gomock.Controller) *MockConfirmAccountTokenPort {
	mock := &MockConfirmAccountTokenPort{ctrl: ctrl}
	mock.recorder = &MockConfirmAccountTokenPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfirmAccountTokenPort) EXPECT() *MockConfirmAccountTokenPortMockRecorder {
	return m.recorder
}

// DeleteConfirmAccountToken mocks base method.
func (m *MockConfirmAccountTokenPort) DeleteConfirmAccountToken(token auth.ConfirmAccountToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteConfirmAccountToken", token)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteConfirmAccountToken indicates an expected call of DeleteConfirmAccountToken.
func (mr *MockConfirmAccountTokenPortMockRecorder) DeleteConfirmAccountToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteConfirmAccountToken", reflect.TypeOf((*MockConfirmAccountTokenPort)(nil).DeleteConfirmAccountToken), token)
}

// GetSuperAdminByConfirmAccountToken mocks base method.
func (m *MockConfirmAccountTokenPort) GetSuperAdminByConfirmAccountToken(tokenString string) (user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSuperAdminByConfirmAccountToken", tokenString)
	ret0, _ := ret[0].(user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSuperAdminByConfirmAccountToken indicates an expected call of GetSuperAdminByConfirmAccountToken.
func (mr *MockConfirmAccountTokenPortMockRecorder) GetSuperAdminByConfirmAccountToken(tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSuperAdminByConfirmAccountToken", reflect.TypeOf((*MockConfirmAccountTokenPort)(nil).GetSuperAdminByConfirmAccountToken), tokenString)
}

// GetSuperAdminConfirmAccountToken mocks base method.
func (m *MockConfirmAccountTokenPort) GetSuperAdminConfirmAccountToken(tokenString string) (auth.ConfirmAccountToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSuperAdminConfirmAccountToken", tokenString)
	ret0, _ := ret[0].(auth.ConfirmAccountToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSuperAdminConfirmAccountToken indicates an expected call of GetSuperAdminConfirmAccountToken.
func (mr *MockConfirmAccountTokenPortMockRecorder) GetSuperAdminConfirmAccountToken(tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSuperAdminConfirmAccountToken", reflect.TypeOf((*MockConfirmAccountTokenPort)(nil).GetSuperAdminConfirmAccountToken), tokenString)
}

// GetTenantConfirmAccountToken mocks base method.
func (m *MockConfirmAccountTokenPort) GetTenantConfirmAccountToken(tenantId, tokenString string) (auth.ConfirmAccountToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenantConfirmAccountToken", tenantId, tokenString)
	ret0, _ := ret[0].(auth.ConfirmAccountToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenantConfirmAccountToken indicates an expected call of GetTenantConfirmAccountToken.
func (mr *MockConfirmAccountTokenPortMockRecorder) GetTenantConfirmAccountToken(tenantId, tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenantConfirmAccountToken", reflect.TypeOf((*MockConfirmAccountTokenPort)(nil).GetTenantConfirmAccountToken), tenantId, tokenString)
}

// GetTenantMemberByConfirmAccountToken mocks base method.
func (m *MockConfirmAccountTokenPort) GetTenantMemberByConfirmAccountToken(tenantId uuid.UUID, tokenString string) (user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenantMemberByConfirmAccountToken", tenantId, tokenString)
	ret0, _ := ret[0].(user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenantMemberByConfirmAccountToken indicates an expected call of GetTenantMemberByConfirmAccountToken.
func (mr *MockConfirmAccountTokenPortMockRecorder) GetTenantMemberByConfirmAccountToken(tenantId, tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenantMemberByConfirmAccountToken", reflect.TypeOf((*MockConfirmAccountTokenPort)(nil).GetTenantMemberByConfirmAccountToken), tenantId, tokenString)
}

// NewConfirmAccountToken mocks base method.
func (m *MockConfirmAccountTokenPort) NewConfirmAccountToken(arg0 user.User) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewConfirmAccountToken", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewConfirmAccountToken indicates an expected call of NewConfirmAccountToken.
func (mr *MockConfirmAccountTokenPortMockRecorder) NewConfirmAccountToken(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewConfirmAccountToken", reflect.TypeOf((*MockConfirmAccountTokenPort)(nil).NewConfirmAccountToken), arg0)
}
