// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/auth (interfaces: ConfirmTokenPort,ChangePasswordTokenPort)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/auth/mocks/ports.go -package=mocks . ConfirmTokenPort,ChangePasswordTokenPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	auth "backend/internal/auth"

	gomock "go.uber.org/mock/gomock"
)

// MockConfirmTokenPort is a mock of ConfirmTokenPort interface.
type MockConfirmTokenPort struct {
	ctrl     *gomock.Controller
	recorder *MockConfirmTokenPortMockRecorder
	isgomock struct{}
}

// MockConfirmTokenPortMockRecorder is the mock recorder for MockConfirmTokenPort.
type MockConfirmTokenPortMockRecorder struct {
	mock *MockConfirmTokenPort
}

// NewMockConfirmTokenPort creates a new mock instance.
func NewMockConfirmTokenPort(ctrl *gomock.Controller) *MockConfirmTokenPort {
	mock := &MockConfirmTokenPort{ctrl: ctrl}
	mock.recorder = &MockConfirmTokenPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfirmTokenPort) EXPECT() *MockConfirmTokenPortMockRecorder {
	return m.recorder
}

// DeleteConfirmAccountToken mocks base method.
func (m *MockConfirmTokenPort) DeleteConfirmAccountToken(tokenId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteConfirmAccountToken", tokenId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteConfirmAccountToken indicates an expected call of DeleteConfirmAccountToken.
func (mr *MockConfirmTokenPortMockRecorder) DeleteConfirmAccountToken(tokenId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteConfirmAccountToken", reflect.TypeOf((*MockConfirmTokenPort)(nil).DeleteConfirmAccountToken), tokenId)
}

// GetConfirmAccountTokenByUserId mocks base method.
func (m *MockConfirmTokenPort) GetConfirmAccountTokenByUserId(userId uint) (*auth.ConfirmToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfirmAccountTokenByUserId", userId)
	ret0, _ := ret[0].(*auth.ConfirmToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfirmAccountTokenByUserId indicates an expected call of GetConfirmAccountTokenByUserId.
func (mr *MockConfirmTokenPortMockRecorder) GetConfirmAccountTokenByUserId(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfirmAccountTokenByUserId", reflect.TypeOf((*MockConfirmTokenPort)(nil).GetConfirmAccountTokenByUserId), userId)
}

// NewConfirmAccountToken mocks base method.
func (m *MockConfirmTokenPort) NewConfirmAccountToken(userId uint) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewConfirmAccountToken", userId)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewConfirmAccountToken indicates an expected call of NewConfirmAccountToken.
func (mr *MockConfirmTokenPortMockRecorder) NewConfirmAccountToken(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewConfirmAccountToken", reflect.TypeOf((*MockConfirmTokenPort)(nil).NewConfirmAccountToken), userId)
}

// MockChangePasswordTokenPort is a mock of ChangePasswordTokenPort interface.
type MockChangePasswordTokenPort struct {
	ctrl     *gomock.Controller
	recorder *MockChangePasswordTokenPortMockRecorder
	isgomock struct{}
}

// MockChangePasswordTokenPortMockRecorder is the mock recorder for MockChangePasswordTokenPort.
type MockChangePasswordTokenPortMockRecorder struct {
	mock *MockChangePasswordTokenPort
}

// NewMockChangePasswordTokenPort creates a new mock instance.
func NewMockChangePasswordTokenPort(ctrl *gomock.Controller) *MockChangePasswordTokenPort {
	mock := &MockChangePasswordTokenPort{ctrl: ctrl}
	mock.recorder = &MockChangePasswordTokenPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChangePasswordTokenPort) EXPECT() *MockChangePasswordTokenPortMockRecorder {
	return m.recorder
}

// DeleteChangePasswordToken mocks base method.
func (m *MockChangePasswordTokenPort) DeleteChangePasswordToken(tokenId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChangePasswordToken", tokenId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChangePasswordToken indicates an expected call of DeleteChangePasswordToken.
func (mr *MockChangePasswordTokenPortMockRecorder) DeleteChangePasswordToken(tokenId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChangePasswordToken", reflect.TypeOf((*MockChangePasswordTokenPort)(nil).DeleteChangePasswordToken), tokenId)
}

// GetChangePasswordTokenByUserId mocks base method.
func (m *MockChangePasswordTokenPort) GetChangePasswordTokenByUserId(userId uint) (*auth.ChangePasswordToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChangePasswordTokenByUserId", userId)
	ret0, _ := ret[0].(*auth.ChangePasswordToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChangePasswordTokenByUserId indicates an expected call of GetChangePasswordTokenByUserId.
func (mr *MockChangePasswordTokenPortMockRecorder) GetChangePasswordTokenByUserId(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChangePasswordTokenByUserId", reflect.TypeOf((*MockChangePasswordTokenPort)(nil).GetChangePasswordTokenByUserId), userId)
}

// SaveChangePasswordToken mocks base method.
func (m *MockChangePasswordTokenPort) SaveChangePasswordToken(token auth.ChangePasswordToken) (*auth.ChangePasswordToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveChangePasswordToken", token)
	ret0, _ := ret[0].(*auth.ChangePasswordToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveChangePasswordToken indicates an expected call of SaveChangePasswordToken.
func (mr *MockChangePasswordTokenPortMockRecorder) SaveChangePasswordToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveChangePasswordToken", reflect.TypeOf((*MockChangePasswordTokenPort)(nil).SaveChangePasswordToken), token)
}
