// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/auth (interfaces: ForgotPasswordTokenPort,SendChangePasswordEmailPort)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/auth/mocks/ports_change_password.go -package=mocks . ForgotPasswordTokenPort,SendChangePasswordEmailPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	auth "backend/internal/auth"
	user "backend/internal/user"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockForgotPasswordTokenPort is a mock of ForgotPasswordTokenPort interface.
type MockForgotPasswordTokenPort struct {
	ctrl     *gomock.Controller
	recorder *MockForgotPasswordTokenPortMockRecorder
	isgomock struct{}
}

// MockForgotPasswordTokenPortMockRecorder is the mock recorder for MockForgotPasswordTokenPort.
type MockForgotPasswordTokenPortMockRecorder struct {
	mock *MockForgotPasswordTokenPort
}

// NewMockForgotPasswordTokenPort creates a new mock instance.
func NewMockForgotPasswordTokenPort(ctrl *gomock.Controller) *MockForgotPasswordTokenPort {
	mock := &MockForgotPasswordTokenPort{ctrl: ctrl}
	mock.recorder = &MockForgotPasswordTokenPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForgotPasswordTokenPort) EXPECT() *MockForgotPasswordTokenPortMockRecorder {
	return m.recorder
}

// DeleteForgotPasswordToken mocks base method.
func (m *MockForgotPasswordTokenPort) DeleteForgotPasswordToken(token auth.ForgotPasswordToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteForgotPasswordToken", token)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteForgotPasswordToken indicates an expected call of DeleteForgotPasswordToken.
func (mr *MockForgotPasswordTokenPortMockRecorder) DeleteForgotPasswordToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteForgotPasswordToken", reflect.TypeOf((*MockForgotPasswordTokenPort)(nil).DeleteForgotPasswordToken), token)
}

// GetSuperAdminByForgotPasswordToken mocks base method.
func (m *MockForgotPasswordTokenPort) GetSuperAdminByForgotPasswordToken(tokenString string) (user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSuperAdminByForgotPasswordToken", tokenString)
	ret0, _ := ret[0].(user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSuperAdminByForgotPasswordToken indicates an expected call of GetSuperAdminByForgotPasswordToken.
func (mr *MockForgotPasswordTokenPortMockRecorder) GetSuperAdminByForgotPasswordToken(tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSuperAdminByForgotPasswordToken", reflect.TypeOf((*MockForgotPasswordTokenPort)(nil).GetSuperAdminByForgotPasswordToken), tokenString)
}

// GetSuperAdminForgotPasswordToken mocks base method.
func (m *MockForgotPasswordTokenPort) GetSuperAdminForgotPasswordToken(tokenString string) (auth.ForgotPasswordToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSuperAdminForgotPasswordToken", tokenString)
	ret0, _ := ret[0].(auth.ForgotPasswordToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSuperAdminForgotPasswordToken indicates an expected call of GetSuperAdminForgotPasswordToken.
func (mr *MockForgotPasswordTokenPortMockRecorder) GetSuperAdminForgotPasswordToken(tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSuperAdminForgotPasswordToken", reflect.TypeOf((*MockForgotPasswordTokenPort)(nil).GetSuperAdminForgotPasswordToken), tokenString)
}

// GetTenantForgotPasswordToken mocks base method.
func (m *MockForgotPasswordTokenPort) GetTenantForgotPasswordToken(tenantId uuid.UUID, tokenString string) (auth.ForgotPasswordToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenantForgotPasswordToken", tenantId, tokenString)
	ret0, _ := ret[0].(auth.ForgotPasswordToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenantForgotPasswordToken indicates an expected call of GetTenantForgotPasswordToken.
func (mr *MockForgotPasswordTokenPortMockRecorder) GetTenantForgotPasswordToken(tenantId, tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenantForgotPasswordToken", reflect.TypeOf((*MockForgotPasswordTokenPort)(nil).GetTenantForgotPasswordToken), tenantId, tokenString)
}

// GetTenantMemberByForgotPasswordToken mocks base method.
func (m *MockForgotPasswordTokenPort) GetTenantMemberByForgotPasswordToken(tenantId uuid.UUID, tokenString string) (user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenantMemberByForgotPasswordToken", tenantId, tokenString)
	ret0, _ := ret[0].(user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenantMemberByForgotPasswordToken indicates an expected call of GetTenantMemberByForgotPasswordToken.
func (mr *MockForgotPasswordTokenPortMockRecorder) GetTenantMemberByForgotPasswordToken(tenantId, tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenantMemberByForgotPasswordToken", reflect.TypeOf((*MockForgotPasswordTokenPort)(nil).GetTenantMemberByForgotPasswordToken), tenantId, tokenString)
}

// NewForgotPasswordToken mocks base method.
func (m *MockForgotPasswordTokenPort) NewForgotPasswordToken(arg0 user.User) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewForgotPasswordToken", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewForgotPasswordToken indicates an expected call of NewForgotPasswordToken.
func (mr *MockForgotPasswordTokenPortMockRecorder) NewForgotPasswordToken(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewForgotPasswordToken", reflect.TypeOf((*MockForgotPasswordTokenPort)(nil).NewForgotPasswordToken), arg0)
}

// MockSendChangePasswordEmailPort is a mock of SendChangePasswordEmailPort interface.
type MockSendChangePasswordEmailPort struct {
	ctrl     *gomock.Controller
	recorder *MockSendChangePasswordEmailPortMockRecorder
	isgomock struct{}
}

// MockSendChangePasswordEmailPortMockRecorder is the mock recorder for MockSendChangePasswordEmailPort.
type MockSendChangePasswordEmailPortMockRecorder struct {
	mock *MockSendChangePasswordEmailPort
}

// NewMockSendChangePasswordEmailPort creates a new mock instance.
func NewMockSendChangePasswordEmailPort(ctrl *gomock.Controller) *MockSendChangePasswordEmailPort {
	mock := &MockSendChangePasswordEmailPort{ctrl: ctrl}
	mock.recorder = &MockSendChangePasswordEmailPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSendChangePasswordEmailPort) EXPECT() *MockSendChangePasswordEmailPortMockRecorder {
	return m.recorder
}

// SendChangePasswordEmail mocks base method.
func (m *MockSendChangePasswordEmailPort) SendChangePasswordEmail(toAddr, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendChangePasswordEmail", toAddr, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendChangePasswordEmail indicates an expected call of SendChangePasswordEmail.
func (mr *MockSendChangePasswordEmailPortMockRecorder) SendChangePasswordEmail(toAddr, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendChangePasswordEmail", reflect.TypeOf((*MockSendChangePasswordEmailPort)(nil).SendChangePasswordEmail), toAddr, token)
}
