// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/auth (interfaces: SuperAdminPasswordTokenRepository,TenantPasswordTokenRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/auth/mocks/repository_change_password.go -package=mocks . SuperAdminPasswordTokenRepository,TenantPasswordTokenRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	auth "backend/internal/auth"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSuperAdminPasswordTokenRepository is a mock of SuperAdminPasswordTokenRepository interface.
type MockSuperAdminPasswordTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSuperAdminPasswordTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockSuperAdminPasswordTokenRepositoryMockRecorder is the mock recorder for MockSuperAdminPasswordTokenRepository.
type MockSuperAdminPasswordTokenRepositoryMockRecorder struct {
	mock *MockSuperAdminPasswordTokenRepository
}

// NewMockSuperAdminPasswordTokenRepository creates a new mock instance.
func NewMockSuperAdminPasswordTokenRepository(ctrl *gomock.Controller) *MockSuperAdminPasswordTokenRepository {
	mock := &MockSuperAdminPasswordTokenRepository{ctrl: ctrl}
	mock.recorder = &MockSuperAdminPasswordTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSuperAdminPasswordTokenRepository) EXPECT() *MockSuperAdminPasswordTokenRepositoryMockRecorder {
	return m.recorder
}

// DeleteToken mocks base method.
func (m *MockSuperAdminPasswordTokenRepository) DeleteToken(entity *auth.SuperAdminPasswordTokenEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteToken", entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteToken indicates an expected call of DeleteToken.
func (mr *MockSuperAdminPasswordTokenRepositoryMockRecorder) DeleteToken(entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteToken", reflect.TypeOf((*MockSuperAdminPasswordTokenRepository)(nil).DeleteToken), entity)
}

// GetToken mocks base method.
func (m *MockSuperAdminPasswordTokenRepository) GetToken(tokenString string) (*auth.SuperAdminPasswordTokenEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetToken", tokenString)
	ret0, _ := ret[0].(*auth.SuperAdminPasswordTokenEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetToken indicates an expected call of GetToken.
func (mr *MockSuperAdminPasswordTokenRepositoryMockRecorder) GetToken(tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToken", reflect.TypeOf((*MockSuperAdminPasswordTokenRepository)(nil).GetToken), tokenString)
}

// GetTokenWithUser mocks base method.
func (m *MockSuperAdminPasswordTokenRepository) GetTokenWithUser(tokenString string) (*auth.SuperAdminPasswordTokenEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenWithUser", tokenString)
	ret0, _ := ret[0].(*auth.SuperAdminPasswordTokenEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenWithUser indicates an expected call of GetTokenWithUser.
func (mr *MockSuperAdminPasswordTokenRepositoryMockRecorder) GetTokenWithUser(tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenWithUser", reflect.TypeOf((*MockSuperAdminPasswordTokenRepository)(nil).GetTokenWithUser), tokenString)
}

// SaveToken mocks base method.
func (m *MockSuperAdminPasswordTokenRepository) SaveToken(entity *auth.SuperAdminPasswordTokenEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveToken", entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveToken indicates an expected call of SaveToken.
func (mr *MockSuperAdminPasswordTokenRepositoryMockRecorder) SaveToken(entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveToken", reflect.TypeOf((*MockSuperAdminPasswordTokenRepository)(nil).SaveToken), entity)
}

// MockTenantPasswordTokenRepository is a mock of TenantPasswordTokenRepository interface.
type MockTenantPasswordTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTenantPasswordTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockTenantPasswordTokenRepositoryMockRecorder is the mock recorder for MockTenantPasswordTokenRepository.
type MockTenantPasswordTokenRepositoryMockRecorder struct {
	mock *MockTenantPasswordTokenRepository
}

// NewMockTenantPasswordTokenRepository creates a new mock instance.
func NewMockTenantPasswordTokenRepository(ctrl *gomock.Controller) *MockTenantPasswordTokenRepository {
	mock := &MockTenantPasswordTokenRepository{ctrl: ctrl}
	mock.recorder = &MockTenantPasswordTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantPasswordTokenRepository) EXPECT() *MockTenantPasswordTokenRepositoryMockRecorder {
	return m.recorder
}

// DeleteToken mocks base method.
func (m *MockTenantPasswordTokenRepository) DeleteToken(entity *auth.TenantPasswordTokenEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteToken", entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteToken indicates an expected call of DeleteToken.
func (mr *MockTenantPasswordTokenRepositoryMockRecorder) DeleteToken(entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteToken", reflect.TypeOf((*MockTenantPasswordTokenRepository)(nil).DeleteToken), entity)
}

// GetToken mocks base method.
func (m *MockTenantPasswordTokenRepository) GetToken(tenantId, tokenString string) (*auth.TenantPasswordTokenEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetToken", tenantId, tokenString)
	ret0, _ := ret[0].(*auth.TenantPasswordTokenEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetToken indicates an expected call of GetToken.
func (mr *MockTenantPasswordTokenRepositoryMockRecorder) GetToken(tenantId, tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToken", reflect.TypeOf((*MockTenantPasswordTokenRepository)(nil).GetToken), tenantId, tokenString)
}

// GetTokenWithUser mocks base method.
func (m *MockTenantPasswordTokenRepository) GetTokenWithUser(tenantId, tokenString string) (*auth.TenantPasswordTokenEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenWithUser", tenantId, tokenString)
	ret0, _ := ret[0].(*auth.TenantPasswordTokenEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenWithUser indicates an expected call of GetTokenWithUser.
func (mr *MockTenantPasswordTokenRepositoryMockRecorder) GetTokenWithUser(tenantId, tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenWithUser", reflect.TypeOf((*MockTenantPasswordTokenRepository)(nil).GetTokenWithUser), tenantId, tokenString)
}

// SaveToken mocks base method.
func (m *MockTenantPasswordTokenRepository) SaveToken(entity *auth.TenantPasswordTokenEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveToken", entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveToken indicates an expected call of SaveToken.
func (mr *MockTenantPasswordTokenRepositoryMockRecorder) SaveToken(entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveToken", reflect.TypeOf((*MockTenantPasswordTokenRepository)(nil).SaveToken), entity)
}
