// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/auth (interfaces: SuperAdminConfirmTokenRepository,TenantConfirmTokenRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/auth/mocks/repository_confirm_account.go -package=mocks . SuperAdminConfirmTokenRepository,TenantConfirmTokenRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	auth "backend/internal/auth"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSuperAdminConfirmTokenRepository is a mock of SuperAdminConfirmTokenRepository interface.
type MockSuperAdminConfirmTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSuperAdminConfirmTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockSuperAdminConfirmTokenRepositoryMockRecorder is the mock recorder for MockSuperAdminConfirmTokenRepository.
type MockSuperAdminConfirmTokenRepositoryMockRecorder struct {
	mock *MockSuperAdminConfirmTokenRepository
}

// NewMockSuperAdminConfirmTokenRepository creates a new mock instance.
func NewMockSuperAdminConfirmTokenRepository(ctrl *gomock.Controller) *MockSuperAdminConfirmTokenRepository {
	mock := &MockSuperAdminConfirmTokenRepository{ctrl: ctrl}
	mock.recorder = &MockSuperAdminConfirmTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSuperAdminConfirmTokenRepository) EXPECT() *MockSuperAdminConfirmTokenRepositoryMockRecorder {
	return m.recorder
}

// DeleteToken mocks base method.
func (m *MockSuperAdminConfirmTokenRepository) DeleteToken(entity *auth.SuperAdminConfirmTokenEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteToken", entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteToken indicates an expected call of DeleteToken.
func (mr *MockSuperAdminConfirmTokenRepositoryMockRecorder) DeleteToken(entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteToken", reflect.TypeOf((*MockSuperAdminConfirmTokenRepository)(nil).DeleteToken), entity)
}

// GetToken mocks base method.
func (m *MockSuperAdminConfirmTokenRepository) GetToken(tokenString string) (*auth.SuperAdminConfirmTokenEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetToken", tokenString)
	ret0, _ := ret[0].(*auth.SuperAdminConfirmTokenEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetToken indicates an expected call of GetToken.
func (mr *MockSuperAdminConfirmTokenRepositoryMockRecorder) GetToken(tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToken", reflect.TypeOf((*MockSuperAdminConfirmTokenRepository)(nil).GetToken), tokenString)
}

// GetTokenWithUser mocks base method.
func (m *MockSuperAdminConfirmTokenRepository) GetTokenWithUser(tokenString string) (*auth.SuperAdminConfirmTokenEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenWithUser", tokenString)
	ret0, _ := ret[0].(*auth.SuperAdminConfirmTokenEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenWithUser indicates an expected call of GetTokenWithUser.
func (mr *MockSuperAdminConfirmTokenRepositoryMockRecorder) GetTokenWithUser(tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenWithUser", reflect.TypeOf((*MockSuperAdminConfirmTokenRepository)(nil).GetTokenWithUser), tokenString)
}

// SaveToken mocks base method.
func (m *MockSuperAdminConfirmTokenRepository) SaveToken(entity *auth.SuperAdminConfirmTokenEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveToken", entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveToken indicates an expected call of SaveToken.
func (mr *MockSuperAdminConfirmTokenRepositoryMockRecorder) SaveToken(entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveToken", reflect.TypeOf((*MockSuperAdminConfirmTokenRepository)(nil).SaveToken), entity)
}

// MockTenantConfirmTokenRepository is a mock of TenantConfirmTokenRepository interface.
type MockTenantConfirmTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTenantConfirmTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockTenantConfirmTokenRepositoryMockRecorder is the mock recorder for MockTenantConfirmTokenRepository.
type MockTenantConfirmTokenRepositoryMockRecorder struct {
	mock *MockTenantConfirmTokenRepository
}

// NewMockTenantConfirmTokenRepository creates a new mock instance.
func NewMockTenantConfirmTokenRepository(ctrl *gomock.Controller) *MockTenantConfirmTokenRepository {
	mock := &MockTenantConfirmTokenRepository{ctrl: ctrl}
	mock.recorder = &MockTenantConfirmTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantConfirmTokenRepository) EXPECT() *MockTenantConfirmTokenRepositoryMockRecorder {
	return m.recorder
}

// DeleteToken mocks base method.
func (m *MockTenantConfirmTokenRepository) DeleteToken(entity *auth.TenantConfirmTokenEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteToken", entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteToken indicates an expected call of DeleteToken.
func (mr *MockTenantConfirmTokenRepositoryMockRecorder) DeleteToken(entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteToken", reflect.TypeOf((*MockTenantConfirmTokenRepository)(nil).DeleteToken), entity)
}

// GetToken mocks base method.
func (m *MockTenantConfirmTokenRepository) GetToken(tenantId, tokenString string) (*auth.TenantConfirmTokenEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetToken", tenantId, tokenString)
	ret0, _ := ret[0].(*auth.TenantConfirmTokenEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetToken indicates an expected call of GetToken.
func (mr *MockTenantConfirmTokenRepositoryMockRecorder) GetToken(tenantId, tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToken", reflect.TypeOf((*MockTenantConfirmTokenRepository)(nil).GetToken), tenantId, tokenString)
}

// GetTokenWithUser mocks base method.
func (m *MockTenantConfirmTokenRepository) GetTokenWithUser(tenantId, tokenString string) (*auth.TenantConfirmTokenEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenWithUser", tenantId, tokenString)
	ret0, _ := ret[0].(*auth.TenantConfirmTokenEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenWithUser indicates an expected call of GetTokenWithUser.
func (mr *MockTenantConfirmTokenRepositoryMockRecorder) GetTokenWithUser(tenantId, tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenWithUser", reflect.TypeOf((*MockTenantConfirmTokenRepository)(nil).GetTokenWithUser), tenantId, tokenString)
}

// SaveToken mocks base method.
func (m *MockTenantConfirmTokenRepository) SaveToken(entity *auth.TenantConfirmTokenEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveToken", entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveToken indicates an expected call of SaveToken.
func (mr *MockTenantConfirmTokenRepositoryMockRecorder) SaveToken(entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveToken", reflect.TypeOf((*MockTenantConfirmTokenRepository)(nil).SaveToken), entity)
}
