// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/auth (interfaces: LoginUserUseCase,LogoutUserUseCase,ConfirmAccountUseCase,VerifyConfirmAccountTokenUseCase)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/auth/mocks/use_cases.go -package=mocks . LoginUserUseCase,LogoutUserUseCase,ConfirmAccountUseCase,VerifyConfirmAccountTokenUseCase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	auth "backend/internal/auth"
	user "backend/internal/user"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLoginUserUseCase is a mock of LoginUserUseCase interface.
type MockLoginUserUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockLoginUserUseCaseMockRecorder
	isgomock struct{}
}

// MockLoginUserUseCaseMockRecorder is the mock recorder for MockLoginUserUseCase.
type MockLoginUserUseCaseMockRecorder struct {
	mock *MockLoginUserUseCase
}

// NewMockLoginUserUseCase creates a new mock instance.
func NewMockLoginUserUseCase(ctrl *gomock.Controller) *MockLoginUserUseCase {
	mock := &MockLoginUserUseCase{ctrl: ctrl}
	mock.recorder = &MockLoginUserUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoginUserUseCase) EXPECT() *MockLoginUserUseCaseMockRecorder {
	return m.recorder
}

// LoginUser mocks base method.
func (m *MockLoginUserUseCase) LoginUser(arg0 auth.LoginUserCommand) (user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginUser", arg0)
	ret0, _ := ret[0].(user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoginUser indicates an expected call of LoginUser.
func (mr *MockLoginUserUseCaseMockRecorder) LoginUser(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginUser", reflect.TypeOf((*MockLoginUserUseCase)(nil).LoginUser), arg0)
}

// MockLogoutUserUseCase is a mock of LogoutUserUseCase interface.
type MockLogoutUserUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockLogoutUserUseCaseMockRecorder
	isgomock struct{}
}

// MockLogoutUserUseCaseMockRecorder is the mock recorder for MockLogoutUserUseCase.
type MockLogoutUserUseCaseMockRecorder struct {
	mock *MockLogoutUserUseCase
}

// NewMockLogoutUserUseCase creates a new mock instance.
func NewMockLogoutUserUseCase(ctrl *gomock.Controller) *MockLogoutUserUseCase {
	mock := &MockLogoutUserUseCase{ctrl: ctrl}
	mock.recorder = &MockLogoutUserUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogoutUserUseCase) EXPECT() *MockLogoutUserUseCaseMockRecorder {
	return m.recorder
}

// LogoutUser mocks base method.
func (m *MockLogoutUserUseCase) LogoutUser(arg0 auth.LogoutUserCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogoutUser", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogoutUser indicates an expected call of LogoutUser.
func (mr *MockLogoutUserUseCaseMockRecorder) LogoutUser(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogoutUser", reflect.TypeOf((*MockLogoutUserUseCase)(nil).LogoutUser), arg0)
}

// MockConfirmAccountUseCase is a mock of ConfirmAccountUseCase interface.
type MockConfirmAccountUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockConfirmAccountUseCaseMockRecorder
	isgomock struct{}
}

// MockConfirmAccountUseCaseMockRecorder is the mock recorder for MockConfirmAccountUseCase.
type MockConfirmAccountUseCaseMockRecorder struct {
	mock *MockConfirmAccountUseCase
}

// NewMockConfirmAccountUseCase creates a new mock instance.
func NewMockConfirmAccountUseCase(ctrl *gomock.Controller) *MockConfirmAccountUseCase {
	mock := &MockConfirmAccountUseCase{ctrl: ctrl}
	mock.recorder = &MockConfirmAccountUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfirmAccountUseCase) EXPECT() *MockConfirmAccountUseCaseMockRecorder {
	return m.recorder
}

// ConfirmAccount mocks base method.
func (m *MockConfirmAccountUseCase) ConfirmAccount(arg0 auth.ConfirmAccountCommand) (user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmAccount", arg0)
	ret0, _ := ret[0].(user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConfirmAccount indicates an expected call of ConfirmAccount.
func (mr *MockConfirmAccountUseCaseMockRecorder) ConfirmAccount(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmAccount", reflect.TypeOf((*MockConfirmAccountUseCase)(nil).ConfirmAccount), arg0)
}

// MockVerifyConfirmAccountTokenUseCase is a mock of VerifyConfirmAccountTokenUseCase interface.
type MockVerifyConfirmAccountTokenUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockVerifyConfirmAccountTokenUseCaseMockRecorder
	isgomock struct{}
}

// MockVerifyConfirmAccountTokenUseCaseMockRecorder is the mock recorder for MockVerifyConfirmAccountTokenUseCase.
type MockVerifyConfirmAccountTokenUseCaseMockRecorder struct {
	mock *MockVerifyConfirmAccountTokenUseCase
}

// NewMockVerifyConfirmAccountTokenUseCase creates a new mock instance.
func NewMockVerifyConfirmAccountTokenUseCase(ctrl *gomock.Controller) *MockVerifyConfirmAccountTokenUseCase {
	mock := &MockVerifyConfirmAccountTokenUseCase{ctrl: ctrl}
	mock.recorder = &MockVerifyConfirmAccountTokenUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVerifyConfirmAccountTokenUseCase) EXPECT() *MockVerifyConfirmAccountTokenUseCaseMockRecorder {
	return m.recorder
}

// VerifyConfirmAccountToken mocks base method.
func (m *MockVerifyConfirmAccountTokenUseCase) VerifyConfirmAccountToken(arg0 auth.VerifyConfirmAccountTokenCommand) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyConfirmAccountToken", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyConfirmAccountToken indicates an expected call of VerifyConfirmAccountToken.
func (mr *MockVerifyConfirmAccountTokenUseCaseMockRecorder) VerifyConfirmAccountToken(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyConfirmAccountToken", reflect.TypeOf((*MockVerifyConfirmAccountTokenUseCase)(nil).VerifyConfirmAccountToken), arg0)
}
