// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/historical_data (interfaces: GetHistoricalDataPort)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/historical_data/mocks/ports.go -package=mocks . GetHistoricalDataPort
//

package mocks

import (
	historical_data "backend/internal/historical_data"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

type MockGetHistoricalDataPort struct {
	ctrl     *gomock.Controller
	recorder *MockGetHistoricalDataPortMockRecorder
	isgomock struct{}
}

type MockGetHistoricalDataPortMockRecorder struct {
	mock *MockGetHistoricalDataPort
}

func NewMockGetHistoricalDataPort(ctrl *gomock.Controller) *MockGetHistoricalDataPort {
	mock := &MockGetHistoricalDataPort{ctrl: ctrl}
	mock.recorder = &MockGetHistoricalDataPortMockRecorder{mock}
	return mock
}

func (m *MockGetHistoricalDataPort) EXPECT() *MockGetHistoricalDataPortMockRecorder {
	return m.recorder
}

func (m *MockGetHistoricalDataPort) GetSensorHistoricalData(
	tenantId uuid.UUID,
	sensorId uuid.UUID,
	filter historical_data.HistoricalDataFilter,
) ([]historical_data.HistoricalSample, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSensorHistoricalData", tenantId, sensorId, filter)
	ret0, _ := ret[0].([]historical_data.HistoricalSample)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockGetHistoricalDataPortMockRecorder) GetSensorHistoricalData(
	tenantId, sensorId, filter any,
) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock,
		"GetSensorHistoricalData",
		reflect.TypeOf((*MockGetHistoricalDataPort)(nil).GetSensorHistoricalData),
		tenantId,
		sensorId,
		filter,
	)
}
