// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/historical_data (interfaces: GetSensorHistoricalDataUseCase)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/historical_data/mocks/use_cases.go -package=mocks . GetSensorHistoricalDataUseCase
//

package mocks

import (
	historical_data "backend/internal/historical_data"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

type MockGetSensorHistoricalDataUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetSensorHistoricalDataUseCaseMockRecorder
	isgomock struct{}
}

type MockGetSensorHistoricalDataUseCaseMockRecorder struct {
	mock *MockGetSensorHistoricalDataUseCase
}

func NewMockGetSensorHistoricalDataUseCase(ctrl *gomock.Controller) *MockGetSensorHistoricalDataUseCase {
	mock := &MockGetSensorHistoricalDataUseCase{ctrl: ctrl}
	mock.recorder = &MockGetSensorHistoricalDataUseCaseMockRecorder{mock}
	return mock
}

func (m *MockGetSensorHistoricalDataUseCase) EXPECT() *MockGetSensorHistoricalDataUseCaseMockRecorder {
	return m.recorder
}

func (m *MockGetSensorHistoricalDataUseCase) GetSensorHistoricalData(
	cmd historical_data.GetSensorHistoricalDataCommand,
) ([]historical_data.HistoricalSample, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSensorHistoricalData", cmd)
	ret0, _ := ret[0].([]historical_data.HistoricalSample)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockGetSensorHistoricalDataUseCaseMockRecorder) GetSensorHistoricalData(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock,
		"GetSensorHistoricalData",
		reflect.TypeOf((*MockGetSensorHistoricalDataUseCase)(nil).GetSensorHistoricalData),
		cmd,
	)
}
