services:
  dashboard:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    user: vscode
    env_file:
      - ../Infrastructure/.env
      - .env
    volumes:
      - ..:/workspaces/app:cached
    command: sleep infinity
    environment:
      DASHBOARD_CREDS_PATH: dashboard.creds
      TEST_CREDS_PATH: admin_test.creds
      CA_PEM_PATH: ca.pem
      PORT: ${PORT}
      MAIL_ADAPTER: ${MAIL_ADAPTER}
      TOKEN_LENGTH: ${TOKEN_LENGTH}
      TOKEN_DURATION: ${TOKEN_DURATION}
      BCRYPT_COST: ${BCRYPT_COST}
      AUTH_TOKEN_DURATION: ${AUTH_TOKEN_DURATION}
      AUTH_TOKEN_SECRET: ${AUTH_TOKEN_SECRET}
      APP_URL: ${APP_URL}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_FROM: ${SMTP_FROM}
    depends_on:
      timescale:
        condition: service_healthy
      cloud-db:
        condition: service_healthy
      nats:
        condition: service_started

include:
  - path: ../Infrastructure/docker-compose.yml