// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/tenant (interfaces: GetTenantPort,GetTenantsPort)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/tenant/mocks/ports.go -package=mocks . GetTenantPort,GetTenantsPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	tenant "backend/internal/tenant"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockGetTenantPort is a mock of GetTenantPort interface.
type MockGetTenantPort struct {
	ctrl     *gomock.Controller
	recorder *MockGetTenantPortMockRecorder
	isgomock struct{}
}

// MockGetTenantPortMockRecorder is the mock recorder for MockGetTenantPort.
type MockGetTenantPortMockRecorder struct {
	mock *MockGetTenantPort
}

// NewMockGetTenantPort creates a new mock instance.
func NewMockGetTenantPort(ctrl *gomock.Controller) *MockGetTenantPort {
	mock := &MockGetTenantPort{ctrl: ctrl}
	mock.recorder = &MockGetTenantPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetTenantPort) EXPECT() *MockGetTenantPortMockRecorder {
	return m.recorder
}

// GetTenant mocks base method.
func (m *MockGetTenantPort) GetTenant(tenantId uuid.UUID) (tenant.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenant", tenantId)
	ret0, _ := ret[0].(tenant.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenant indicates an expected call of GetTenant.
func (mr *MockGetTenantPortMockRecorder) GetTenant(tenantId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenant", reflect.TypeOf((*MockGetTenantPort)(nil).GetTenant), tenantId)
}

// MockGetTenantsPort is a mock of GetTenantsPort interface.
type MockGetTenantsPort struct {
	ctrl     *gomock.Controller
	recorder *MockGetTenantsPortMockRecorder
	isgomock struct{}
}

// MockGetTenantsPortMockRecorder is the mock recorder for MockGetTenantsPort.
type MockGetTenantsPortMockRecorder struct {
	mock *MockGetTenantsPort
}

// NewMockGetTenantsPort creates a new mock instance.
func NewMockGetTenantsPort(ctrl *gomock.Controller) *MockGetTenantsPort {
	mock := &MockGetTenantsPort{ctrl: ctrl}
	mock.recorder = &MockGetTenantsPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetTenantsPort) EXPECT() *MockGetTenantsPortMockRecorder {
	return m.recorder
}

// GetTenants mocks base method.
func (m *MockGetTenantsPort) GetTenants() ([]tenant.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenants")
	ret0, _ := ret[0].([]tenant.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenants indicates an expected call of GetTenants.
func (mr *MockGetTenantsPortMockRecorder) GetTenants() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenants", reflect.TypeOf((*MockGetTenantsPort)(nil).GetTenants))
}
