// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/tenant (interfaces: CreateTenantPort,DeleteTenantPort,GetTenantPort,GetTenantsPort,GetTenantByUserPort)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/tenant/mocks/ports.go -package=mocks . CreateTenantPort,DeleteTenantPort,GetTenantPort,GetTenantsPort,GetTenantByUserPort
//

// package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	tenant "backend/internal/tenant"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCreateTenantPort is a mock of CreateTenantPort interface.
type MockCreateTenantPort struct {
	ctrl     *gomock.Controller
	recorder *MockCreateTenantPortMockRecorder
	isgomock struct{}
}

// MockCreateTenantPortMockRecorder is the mock recorder for MockCreateTenantPort.
type MockCreateTenantPortMockRecorder struct {
	mock *MockCreateTenantPort
}

// NewMockCreateTenantPort creates a new mock instance.
func NewMockCreateTenantPort(ctrl *gomock.Controller) *MockCreateTenantPort {
	mock := &MockCreateTenantPort{ctrl: ctrl}
	mock.recorder = &MockCreateTenantPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateTenantPort) EXPECT() *MockCreateTenantPortMockRecorder {
	return m.recorder
}

// CreateTenant mocks base method.
func (m *MockCreateTenantPort) CreateTenant(arg0 tenant.Tenant) (tenant.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTenant", arg0)
	ret0, _ := ret[0].(tenant.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTenant indicates an expected call of CreateTenant.
func (mr *MockCreateTenantPortMockRecorder) CreateTenant(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTenant", reflect.TypeOf((*MockCreateTenantPort)(nil).CreateTenant), arg0)
}

// MockDeleteTenantPort is a mock of DeleteTenantPort interface.
type MockDeleteTenantPort struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteTenantPortMockRecorder
	isgomock struct{}
}

// MockDeleteTenantPortMockRecorder is the mock recorder for MockDeleteTenantPort.
type MockDeleteTenantPortMockRecorder struct {
	mock *MockDeleteTenantPort
}

// NewMockDeleteTenantPort creates a new mock instance.
func NewMockDeleteTenantPort(ctrl *gomock.Controller) *MockDeleteTenantPort {
	mock := &MockDeleteTenantPort{ctrl: ctrl}
	mock.recorder = &MockDeleteTenantPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteTenantPort) EXPECT() *MockDeleteTenantPortMockRecorder {
	return m.recorder
}

// DeleteTenant mocks base method.
func (m *MockDeleteTenantPort) DeleteTenant(tenantId uuid.UUID) (tenant.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTenant", tenantId)
	ret0, _ := ret[0].(tenant.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTenant indicates an expected call of DeleteTenant.
func (mr *MockDeleteTenantPortMockRecorder) DeleteTenant(tenantId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTenant", reflect.TypeOf((*MockDeleteTenantPort)(nil).DeleteTenant), tenantId)
}

// MockGetTenantPort is a mock of GetTenantPort interface.
type MockGetTenantPort struct {
	ctrl     *gomock.Controller
	recorder *MockGetTenantPortMockRecorder
	isgomock struct{}
}

// MockGetTenantPortMockRecorder is the mock recorder for MockGetTenantPort.
type MockGetTenantPortMockRecorder struct {
	mock *MockGetTenantPort
}

// NewMockGetTenantPort creates a new mock instance.
func NewMockGetTenantPort(ctrl *gomock.Controller) *MockGetTenantPort {
	mock := &MockGetTenantPort{ctrl: ctrl}
	mock.recorder = &MockGetTenantPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetTenantPort) EXPECT() *MockGetTenantPortMockRecorder {
	return m.recorder
}

// GetTenant mocks base method.
func (m *MockGetTenantPort) GetTenant(tenantId uuid.UUID) (tenant.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenant", tenantId)
	ret0, _ := ret[0].(tenant.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenant indicates an expected call of GetTenant.
func (mr *MockGetTenantPortMockRecorder) GetTenant(tenantId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenant", reflect.TypeOf((*MockGetTenantPort)(nil).GetTenant), tenantId)
}

// MockGetTenantsPort is a mock of GetTenantsPort interface.
type MockGetTenantsPort struct {
	ctrl     *gomock.Controller
	recorder *MockGetTenantsPortMockRecorder
	isgomock struct{}
}

// MockGetTenantsPortMockRecorder is the mock recorder for MockGetTenantsPort.
type MockGetTenantsPortMockRecorder struct {
	mock *MockGetTenantsPort
}

// NewMockGetTenantsPort creates a new mock instance.
func NewMockGetTenantsPort(ctrl *gomock.Controller) *MockGetTenantsPort {
	mock := &MockGetTenantsPort{ctrl: ctrl}
	mock.recorder = &MockGetTenantsPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetTenantsPort) EXPECT() *MockGetTenantsPortMockRecorder {
	return m.recorder
}

// GetTenants mocks base method.
func (m *MockGetTenantsPort) GetTenants() ([]tenant.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenants")
	ret0, _ := ret[0].([]tenant.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenants indicates an expected call of GetTenants.
func (mr *MockGetTenantsPortMockRecorder) GetTenants() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenants", reflect.TypeOf((*MockGetTenantsPort)(nil).GetTenants))
}

// MockGetTenantByUserPort is a mock of GetTenantByUserPort interface.
type MockGetTenantByUserPort struct {
	ctrl     *gomock.Controller
	recorder *MockGetTenantByUserPortMockRecorder
	isgomock struct{}
}

// MockGetTenantByUserPortMockRecorder is the mock recorder for MockGetTenantByUserPort.
type MockGetTenantByUserPortMockRecorder struct {
	mock *MockGetTenantByUserPort
}

// NewMockGetTenantByUserPort creates a new mock instance.
func NewMockGetTenantByUserPort(ctrl *gomock.Controller) *MockGetTenantByUserPort {
	mock := &MockGetTenantByUserPort{ctrl: ctrl}
	mock.recorder = &MockGetTenantByUserPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetTenantByUserPort) EXPECT() *MockGetTenantByUserPortMockRecorder {
	return m.recorder
}

// GetTenantByUser mocks base method.
func (m *MockGetTenantByUserPort) GetTenantByUser(userId uuid.UUID) (tenant.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenantByUser", userId)
	ret0, _ := ret[0].(tenant.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenantByUser indicates an expected call of GetTenantByUser.
func (mr *MockGetTenantByUserPortMockRecorder) GetTenantByUser(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenantByUser", reflect.TypeOf((*MockGetTenantByUserPort)(nil).GetTenantByUser), userId)
}
