// Code generated by MockGen. DO NOT EDIT.
// Source: adapters.go
//
// Generated by this command:
//
//	mockgen -source=adapters.go -destination=../../tests/tenant/mocks/repository_adapter.go -package=mocks TenantRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	tenant "backend/internal/tenant"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTenantRepository is a mock of TenantRepository interface.
type MockTenantRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTenantRepositoryMockRecorder
	isgomock struct{}
}

// MockTenantRepositoryMockRecorder is the mock recorder for MockTenantRepository.
type MockTenantRepositoryMockRecorder struct {
	mock *MockTenantRepository
}

// NewMockTenantRepository creates a new mock instance.
func NewMockTenantRepository(ctrl *gomock.Controller) *MockTenantRepository {
	mock := &MockTenantRepository{ctrl: ctrl}
	mock.recorder = &MockTenantRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantRepository) EXPECT() *MockTenantRepositoryMockRecorder {
	return m.recorder
}

// DeleteTenant mocks base method.
func (m *MockTenantRepository) DeleteTenant(arg0 *tenant.TenantEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTenant", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTenant indicates an expected call of DeleteTenant.
func (mr *MockTenantRepositoryMockRecorder) DeleteTenant(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTenant", reflect.TypeOf((*MockTenantRepository)(nil).DeleteTenant), arg0)
}

// GetAllTenants mocks base method.
func (m *MockTenantRepository) GetAllTenants() ([]tenant.TenantEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTenants")
	ret0, _ := ret[0].([]tenant.TenantEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTenants indicates an expected call of GetAllTenants.
func (mr *MockTenantRepositoryMockRecorder) GetAllTenants() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTenants", reflect.TypeOf((*MockTenantRepository)(nil).GetAllTenants))
}

// GetTenant mocks base method.
func (m *MockTenantRepository) GetTenant(tenantId string) (*tenant.TenantEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenant", tenantId)
	ret0, _ := ret[0].(*tenant.TenantEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenant indicates an expected call of GetTenant.
func (mr *MockTenantRepositoryMockRecorder) GetTenant(tenantId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenant", reflect.TypeOf((*MockTenantRepository)(nil).GetTenant), tenantId)
}

// GetTenants mocks base method.
func (m *MockTenantRepository) GetTenants(offset, limit int) ([]tenant.TenantEntity, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenants", offset, limit)
	ret0, _ := ret[0].([]tenant.TenantEntity)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTenants indicates an expected call of GetTenants.
func (mr *MockTenantRepositoryMockRecorder) GetTenants(offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenants", reflect.TypeOf((*MockTenantRepository)(nil).GetTenants), offset, limit)
}

// SaveTenant mocks base method.
func (m *MockTenantRepository) SaveTenant(arg0 *tenant.TenantEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTenant", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveTenant indicates an expected call of SaveTenant.
func (mr *MockTenantRepositoryMockRecorder) SaveTenant(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTenant", reflect.TypeOf((*MockTenantRepository)(nil).SaveTenant), arg0)
}
