// Code generated by MockGen. DO NOT EDIT.
// Source: controller.go
//
// Generated by this command:
//
//	mockgen -source=controller.go -destination=../../tests/tenant/mocks/use_cases_crud.go -package=mocks CreateTenantUseCase,DeleteTenantUseCase,GetTenantUseCase,GetTenantListUseCase,GetAllTenantsUseCase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	tenant "backend/internal/tenant"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCreateTenantUseCase is a mock of CreateTenantUseCase interface.
type MockCreateTenantUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCreateTenantUseCaseMockRecorder
	isgomock struct{}
}

// MockCreateTenantUseCaseMockRecorder is the mock recorder for MockCreateTenantUseCase.
type MockCreateTenantUseCaseMockRecorder struct {
	mock *MockCreateTenantUseCase
}

// NewMockCreateTenantUseCase creates a new mock instance.
func NewMockCreateTenantUseCase(ctrl *gomock.Controller) *MockCreateTenantUseCase {
	mock := &MockCreateTenantUseCase{ctrl: ctrl}
	mock.recorder = &MockCreateTenantUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateTenantUseCase) EXPECT() *MockCreateTenantUseCaseMockRecorder {
	return m.recorder
}

// CreateTenant mocks base method.
func (m *MockCreateTenantUseCase) CreateTenant(cmd tenant.CreateTenantCommand) (tenant.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTenant", cmd)
	ret0, _ := ret[0].(tenant.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTenant indicates an expected call of CreateTenant.
func (mr *MockCreateTenantUseCaseMockRecorder) CreateTenant(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTenant", reflect.TypeOf((*MockCreateTenantUseCase)(nil).CreateTenant), cmd)
}

// MockDeleteTenantUseCase is a mock of DeleteTenantUseCase interface.
type MockDeleteTenantUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteTenantUseCaseMockRecorder
	isgomock struct{}
}

// MockDeleteTenantUseCaseMockRecorder is the mock recorder for MockDeleteTenantUseCase.
type MockDeleteTenantUseCaseMockRecorder struct {
	mock *MockDeleteTenantUseCase
}

// NewMockDeleteTenantUseCase creates a new mock instance.
func NewMockDeleteTenantUseCase(ctrl *gomock.Controller) *MockDeleteTenantUseCase {
	mock := &MockDeleteTenantUseCase{ctrl: ctrl}
	mock.recorder = &MockDeleteTenantUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteTenantUseCase) EXPECT() *MockDeleteTenantUseCaseMockRecorder {
	return m.recorder
}

// DeleteTenant mocks base method.
func (m *MockDeleteTenantUseCase) DeleteTenant(cmd tenant.DeleteTenantCommand) (tenant.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTenant", cmd)
	ret0, _ := ret[0].(tenant.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTenant indicates an expected call of DeleteTenant.
func (mr *MockDeleteTenantUseCaseMockRecorder) DeleteTenant(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTenant", reflect.TypeOf((*MockDeleteTenantUseCase)(nil).DeleteTenant), cmd)
}

// MockGetTenantUseCase is a mock of GetTenantUseCase interface.
type MockGetTenantUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetTenantUseCaseMockRecorder
	isgomock struct{}
}

// MockGetTenantUseCaseMockRecorder is the mock recorder for MockGetTenantUseCase.
type MockGetTenantUseCaseMockRecorder struct {
	mock *MockGetTenantUseCase
}

// NewMockGetTenantUseCase creates a new mock instance.
func NewMockGetTenantUseCase(ctrl *gomock.Controller) *MockGetTenantUseCase {
	mock := &MockGetTenantUseCase{ctrl: ctrl}
	mock.recorder = &MockGetTenantUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetTenantUseCase) EXPECT() *MockGetTenantUseCaseMockRecorder {
	return m.recorder
}

// GetTenant mocks base method.
func (m *MockGetTenantUseCase) GetTenant(cmd tenant.GetTenantCommand) (tenant.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenant", cmd)
	ret0, _ := ret[0].(tenant.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenant indicates an expected call of GetTenant.
func (mr *MockGetTenantUseCaseMockRecorder) GetTenant(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenant", reflect.TypeOf((*MockGetTenantUseCase)(nil).GetTenant), cmd)
}

// MockGetAllTenantsUseCase is a mock of GetAllTenantsUseCase interface.
type MockGetAllTenantsUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetAllTenantsUseCaseMockRecorder
	isgomock struct{}
}

// MockGetAllTenantsUseCaseMockRecorder is the mock recorder for MockGetAllTenantsUseCase.
type MockGetAllTenantsUseCaseMockRecorder struct {
	mock *MockGetAllTenantsUseCase
}

// NewMockGetAllTenantsUseCase creates a new mock instance.
func NewMockGetAllTenantsUseCase(ctrl *gomock.Controller) *MockGetAllTenantsUseCase {
	mock := &MockGetAllTenantsUseCase{ctrl: ctrl}
	mock.recorder = &MockGetAllTenantsUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetAllTenantsUseCase) EXPECT() *MockGetAllTenantsUseCaseMockRecorder {
	return m.recorder
}

// GetAllTenants mocks base method.
func (m *MockGetAllTenantsUseCase) GetAllTenants() ([]tenant.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTenants")
	ret0, _ := ret[0].([]tenant.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTenants indicates an expected call of GetAllTenants.
func (mr *MockGetAllTenantsUseCaseMockRecorder) GetAllTenants() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTenants", reflect.TypeOf((*MockGetAllTenantsUseCase)(nil).GetAllTenants))
}

// MockGetTenantListUseCase is a mock of GetTenantListUseCase interface.
type MockGetTenantListUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetTenantListUseCaseMockRecorder
	isgomock struct{}
}

// MockGetTenantListUseCaseMockRecorder is the mock recorder for MockGetTenantListUseCase.
type MockGetTenantListUseCaseMockRecorder struct {
	mock *MockGetTenantListUseCase
}

// NewMockGetTenantListUseCase creates a new mock instance.
func NewMockGetTenantListUseCase(ctrl *gomock.Controller) *MockGetTenantListUseCase {
	mock := &MockGetTenantListUseCase{ctrl: ctrl}
	mock.recorder = &MockGetTenantListUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetTenantListUseCase) EXPECT() *MockGetTenantListUseCaseMockRecorder {
	return m.recorder
}

// GetTenantList mocks base method.
func (m *MockGetTenantListUseCase) GetTenantList(cmd tenant.GetTenantListCommand) ([]tenant.Tenant, uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenantList", cmd)
	ret0, _ := ret[0].([]tenant.Tenant)
	ret1, _ := ret[1].(uint)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTenantList indicates an expected call of GetTenantList.
func (mr *MockGetTenantListUseCaseMockRecorder) GetTenantList(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenantList", reflect.TypeOf((*MockGetTenantListUseCase)(nil).GetTenantList), cmd)
}
