// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/gateway_connection (interfaces: GatewayHelloService)

package mocks

import (
	gateway_connection "backend/internal/gateway_connection"
	"reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGatewayHelloService is a mock of GatewayHelloService interface.
type MockGatewayHelloService struct {
	ctrl     *gomock.Controller
	recorder *MockGatewayHelloServiceMockRecorder
	isgomock struct{}
}

// MockGatewayHelloServiceMockRecorder is the mock recorder for MockGatewayHelloService.
type MockGatewayHelloServiceMockRecorder struct {
	mock *MockGatewayHelloService
}

// NewMockGatewayHelloService creates a new mock instance.
func NewMockGatewayHelloService(ctrl *gomock.Controller) *MockGatewayHelloService {
	mock := &MockGatewayHelloService{ctrl: ctrl}
	mock.recorder = &MockGatewayHelloServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGatewayHelloService) EXPECT() *MockGatewayHelloServiceMockRecorder {
	return m.recorder
}

// ProcessHello mocks base method.
func (m *MockGatewayHelloService) ProcessHello(msg gateway_connection.GatewayHelloMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessHello", msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessHello indicates an expected call of ProcessHello.
func (mr *MockGatewayHelloServiceMockRecorder) ProcessHello(msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessHello", reflect.TypeOf((*MockGatewayHelloService)(nil).ProcessHello), msg)
}
