// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/shared/crypto (interfaces: AuthTokenManager)
//
// Generated by this command:
//
//	mockgen -destination=../../../tests/shared/crypto/mocks/auth_token.go -package=mocks . AuthTokenManager
//

// Package mocks is a generated GoMock package.
package mocks

import (
	identity "backend/internal/shared/identity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthTokenManager is a mock of AuthTokenManager interface.
type MockAuthTokenManager struct {
	ctrl     *gomock.Controller
	recorder *MockAuthTokenManagerMockRecorder
	isgomock struct{}
}

// MockAuthTokenManagerMockRecorder is the mock recorder for MockAuthTokenManager.
type MockAuthTokenManagerMockRecorder struct {
	mock *MockAuthTokenManager
}

// NewMockAuthTokenManager creates a new mock instance.
func NewMockAuthTokenManager(ctrl *gomock.Controller) *MockAuthTokenManager {
	mock := &MockAuthTokenManager{ctrl: ctrl}
	mock.recorder = &MockAuthTokenManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthTokenManager) EXPECT() *MockAuthTokenManagerMockRecorder {
	return m.recorder
}

// GenerateForRequester mocks base method.
func (m *MockAuthTokenManager) GenerateForRequester(requester identity.Requester) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateForRequester", requester)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateForRequester indicates an expected call of GenerateForRequester.
func (mr *MockAuthTokenManagerMockRecorder) GenerateForRequester(requester any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateForRequester", reflect.TypeOf((*MockAuthTokenManager)(nil).GenerateForRequester), requester)
}

// GetRequesterFromToken mocks base method.
func (m *MockAuthTokenManager) GetRequesterFromToken(token string) (identity.Requester, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequesterFromToken", token)
	ret0, _ := ret[0].(identity.Requester)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRequesterFromToken indicates an expected call of GetRequesterFromToken.
func (mr *MockAuthTokenManagerMockRecorder) GetRequesterFromToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequesterFromToken", reflect.TypeOf((*MockAuthTokenManager)(nil).GetRequesterFromToken), token)
}
