// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/shared/crypto (interfaces: SecretHasher)
//
// Generated by this command:
//
//	mockgen -destination=../../../tests/shared/crypto/mocks/secret_hasher.go -package=mocks . SecretHasher
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSecretHasher is a mock of SecretHasher interface.
type MockSecretHasher struct {
	ctrl     *gomock.Controller
	recorder *MockSecretHasherMockRecorder
	isgomock struct{}
}

// MockSecretHasherMockRecorder is the mock recorder for MockSecretHasher.
type MockSecretHasherMockRecorder struct {
	mock *MockSecretHasher
}

// NewMockSecretHasher creates a new mock instance.
func NewMockSecretHasher(ctrl *gomock.Controller) *MockSecretHasher {
	mock := &MockSecretHasher{ctrl: ctrl}
	mock.recorder = &MockSecretHasherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretHasher) EXPECT() *MockSecretHasherMockRecorder {
	return m.recorder
}

// CompareHashAndSecret mocks base method.
func (m *MockSecretHasher) CompareHashAndSecret(hashed, plaintext string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompareHashAndSecret", hashed, plaintext)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompareHashAndSecret indicates an expected call of CompareHashAndSecret.
func (mr *MockSecretHasherMockRecorder) CompareHashAndSecret(hashed, plaintext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompareHashAndSecret", reflect.TypeOf((*MockSecretHasher)(nil).CompareHashAndSecret), hashed, plaintext)
}

// HashSecret mocks base method.
func (m *MockSecretHasher) HashSecret(plaintext string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashSecret", plaintext)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HashSecret indicates an expected call of HashSecret.
func (mr *MockSecretHasherMockRecorder) HashSecret(plaintext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HashSecret", reflect.TypeOf((*MockSecretHasher)(nil).HashSecret), plaintext)
}
