// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/shared/crypto (interfaces: SecurityTokenGenerator)
//
// Generated by this command:
//
//	mockgen -destination=../../../tests/shared/crypto/mocks/security_token.go -package=mocks . SecurityTokenGenerator
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockSecurityTokenGenerator is a mock of SecurityTokenGenerator interface.
type MockSecurityTokenGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockSecurityTokenGeneratorMockRecorder
	isgomock struct{}
}

// MockSecurityTokenGeneratorMockRecorder is the mock recorder for MockSecurityTokenGenerator.
type MockSecurityTokenGeneratorMockRecorder struct {
	mock *MockSecurityTokenGenerator
}

// NewMockSecurityTokenGenerator creates a new mock instance.
func NewMockSecurityTokenGenerator(ctrl *gomock.Controller) *MockSecurityTokenGenerator {
	mock := &MockSecurityTokenGenerator{ctrl: ctrl}
	mock.recorder = &MockSecurityTokenGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecurityTokenGenerator) EXPECT() *MockSecurityTokenGeneratorMockRecorder {
	return m.recorder
}

// ExpiryFromNow mocks base method.
func (m *MockSecurityTokenGenerator) ExpiryFromNow() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpiryFromNow")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// ExpiryFromNow indicates an expected call of ExpiryFromNow.
func (mr *MockSecurityTokenGeneratorMockRecorder) ExpiryFromNow() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpiryFromNow", reflect.TypeOf((*MockSecurityTokenGenerator)(nil).ExpiryFromNow))
}

// GenerateToken mocks base method.
func (m *MockSecurityTokenGenerator) GenerateToken() (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockSecurityTokenGeneratorMockRecorder) GenerateToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockSecurityTokenGenerator)(nil).GenerateToken))
}
