// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/email (interfaces: createMessageStrategy)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/email/mocks/message_strategy.go -package=mocks . createMessageStrategy
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	mail "gopkg.in/mail.v2"
)

// MockcreateMessageStrategy is a mock of createMessageStrategy interface.
type MockcreateMessageStrategy struct {
	ctrl     *gomock.Controller
	recorder *MockcreateMessageStrategyMockRecorder
	isgomock struct{}
}

// MockcreateMessageStrategyMockRecorder is the mock recorder for MockcreateMessageStrategy.
type MockcreateMessageStrategyMockRecorder struct {
	mock *MockcreateMessageStrategy
}

// NewMockcreateMessageStrategy creates a new mock instance.
func NewMockcreateMessageStrategy(ctrl *gomock.Controller) *MockcreateMessageStrategy {
	mock := &MockcreateMessageStrategy{ctrl: ctrl}
	mock.recorder = &MockcreateMessageStrategyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcreateMessageStrategy) EXPECT() *MockcreateMessageStrategyMockRecorder {
	return m.recorder
}

// CreateMessage mocks base method.
func (m *MockcreateMessageStrategy) CreateMessage(fromAddress, toAddress, subject, body string) *mail.Message {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMessage", fromAddress, toAddress, subject, body)
	ret0, _ := ret[0].(*mail.Message)
	return ret0
}

// CreateMessage indicates an expected call of CreateMessage.
func (mr *MockcreateMessageStrategyMockRecorder) CreateMessage(fromAddress, toAddress, subject, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMessage", reflect.TypeOf((*MockcreateMessageStrategy)(nil).CreateMessage), fromAddress, toAddress, subject, body)
}
