// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/email (interfaces: SendEmailPort)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/email/mocks/ports.go -package=mocks . SendEmailPort
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSendEmailPort is a mock of SendEmailPort interface.
type MockSendEmailPort struct {
	ctrl     *gomock.Controller
	recorder *MockSendEmailPortMockRecorder
	isgomock struct{}
}

// MockSendEmailPortMockRecorder is the mock recorder for MockSendEmailPort.
type MockSendEmailPortMockRecorder struct {
	mock *MockSendEmailPort
}

// NewMockSendEmailPort creates a new mock instance.
func NewMockSendEmailPort(ctrl *gomock.Controller) *MockSendEmailPort {
	mock := &MockSendEmailPort{ctrl: ctrl}
	mock.recorder = &MockSendEmailPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSendEmailPort) EXPECT() *MockSendEmailPortMockRecorder {
	return m.recorder
}

// SendChangePasswordEmail mocks base method.
func (m *MockSendEmailPort) SendChangePasswordEmail(toAddr, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendChangePasswordEmail", toAddr, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendChangePasswordEmail indicates an expected call of SendChangePasswordEmail.
func (mr *MockSendEmailPortMockRecorder) SendChangePasswordEmail(toAddr, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendChangePasswordEmail", reflect.TypeOf((*MockSendEmailPort)(nil).SendChangePasswordEmail), toAddr, token)
}

// SendConfirmAccountEmail mocks base method.
func (m *MockSendEmailPort) SendConfirmAccountEmail(toAddr, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendConfirmAccountEmail", toAddr, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendConfirmAccountEmail indicates an expected call of SendConfirmAccountEmail.
func (mr *MockSendEmailPortMockRecorder) SendConfirmAccountEmail(toAddr, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendConfirmAccountEmail", reflect.TypeOf((*MockSendEmailPort)(nil).SendConfirmAccountEmail), toAddr, token)
}
