// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/email (interfaces: smtpSender)
//
// Generated by this command:
//
//	mockgen -destination=../../tests/email/mocks/sender.go -package=mocks . smtpSender
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	mail "gopkg.in/mail.v2"
)

// MocksmtpSender is a mock of smtpSender interface.
type MocksmtpSender struct {
	ctrl     *gomock.Controller
	recorder *MocksmtpSenderMockRecorder
	isgomock struct{}
}

// MocksmtpSenderMockRecorder is the mock recorder for MocksmtpSender.
type MocksmtpSenderMockRecorder struct {
	mock *MocksmtpSender
}

// NewMocksmtpSender creates a new mock instance.
func NewMocksmtpSender(ctrl *gomock.Controller) *MocksmtpSender {
	mock := &MocksmtpSender{ctrl: ctrl}
	mock.recorder = &MocksmtpSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksmtpSender) EXPECT() *MocksmtpSenderMockRecorder {
	return m.recorder
}

// DialAndSend mocks base method.
func (m_2 *MocksmtpSender) DialAndSend(m ...*mail.Message) error {
	m_2.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range m {
		varargs = append(varargs, a)
	}
	ret := m_2.ctrl.Call(m_2, "DialAndSend", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DialAndSend indicates an expected call of DialAndSend.
func (mr *MocksmtpSenderMockRecorder) DialAndSend(m ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DialAndSend", reflect.TypeOf((*MocksmtpSender)(nil).DialAndSend), m...)
}
